### ISSUE TITLE
`Lint/UselessMethodDefinition` unaware of differing method arity between parent and child when using `super`

### ISSUE THREAD

**Issue by backus** [rubocop/rubocop#10046]
## Versions

```
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.2)
    parallel (1.20.1)
    parser (3.0.2.0)
      ast (~> 2.4.1)
    rainbow (3.0.0)
    regexp_parser (2.1.1)
    rexml (3.2.5)
    rubocop (1.2.0)
      parallel (~> 1.10)
      parser (>= 2.7.1.5)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8)
      rexml
      rubocop-ast (>= 1.0.1)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 2.0)
    rubocop-ast (1.11.0)
      parser (>= 3.0.1.1)
    ruby-progressbar (1.11.0)
    unicode-display_width (1.7.0)

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  rubocop (= 1.2.0)

BUNDLED WITH
   2.2.6
```

## Code demonstrating bug

```ruby
# frozen_string_literal: true

class Parent
  def initialize(name, options)
    @name    = name
    @options = options
  end

  attr_reader :name, :options
end

class Child < Parent
  def initialize(name, **options)
    super
  end
end

child1 = Child.new('Alice')
child2 = Child.new('Bob', quiet: true)

p child1
p child2
```

#### Demonstration of code's behavior

```sh
$ ruby example.rb
#<Child:0x00007faa9d878a30 @name="Alice", @options={}>
#<Child:0x00007faa9d878918 @name="Bob", @options={:quiet=>true}>
```

## RuboCop's behavior

```sh
Inspecting 1 file
W

Offenses:

example.rb:13:3: W: Lint/UselessMethodDefinition: Useless method definition detected.
  def initialize(name, **options) ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

If I take RuboCop's recommendation: 

```sh
$ bundle exec ruby example.rb
#<Child:0x00007fd02b1f3a80 @name="Alice", @options={}>
#<Child:0x00007fd02b1ebee8 @name="Bob", @options={:quiet=>true}>

$ bundle exec rubocop -A example.rb
Inspecting 1 file
W

Offenses:

example.rb:13:1: C: [Corrected] Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.
example.rb:13:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
example.rb:13:3: W: [Corrected] Lint/UselessMethodDefinition: Useless method definition detected.
  def initialize(name, **options) ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses corrected

$ git diff
diff --git i/example.rb w/example.rb
index 8befde1..2540f5c 100644
--- i/example.rb
+++ w/example.rb
@@ -10,9 +10,6 @@ class Parent
 end

 class Child < Parent
-  def initialize(name, **options)
-    super
-  end
 end

 child1 = Child.new('Alice')

$ bundle exec ruby example.rb
Traceback (most recent call last):
	2: from example.rb:15:in `<main>'
	1: from example.rb:15:in `new'
example.rb:4:in `initialize': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

## Expected Behavior

RuboCop should be aware that the parent method's arity may differ from the child's

**Comment by bbatsov** [comment]
Reopened — still reproduces on master (1.88). The autocorrect deletes a subclass's `def initialize(name, **options); super; end`, but the parent's `initialize` has a different arity, so e.g. `Child.new('Alice')` goes from working to raising `ArgumentError`.
