### ISSUE TITLE
rubocop-sorbet :: undefined method `source' for nil:NilClass

### ISSUE THREAD

**Issue by robynelliott** [rubocop/rubocop#10097]
## Actual behavior

```
undefined method `source' for nil:NilClass
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-sorbet-0.6.2/lib/rubocop/cop/sorbet/callback_conditionals_binding.rb:128:in `on_send'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.11.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.11.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.11.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.11.0/lib/rubocop/ast/traversal.rb:154:in `on_class'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.11.0/lib/rubocop/ast/traversal.rb:154:in `on_class'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.11.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cop/team.rb:83:in `investigate'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:309:in `inspect_file'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:253:in `block in do_inspection_loop'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:280:in `loop'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:130:in `block in file_offenses'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:155:in `file_offense_cache'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:129:in `file_offenses'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:120:in `process_file'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:100:in `each'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:100:in `reduce'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/runner.rb:47:in `run'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli.rb:71:in `run_command'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/lib/rubocop/cli.rb:47:in `run'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/exe/rubocop:12:in `block in <top (required)>'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/Users/robynelliott/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.21.0/exe/rubocop:12:in `<top (required)>'
/Users/robynelliott/.rbenv/versions/2.7.3/bin/rubocop:23:in `load'
/Users/robynelliott/.rbenv/versions/2.7.3/bin/rubocop:23:in `<main>'
```

## Steps to reproduce the problem

`rubocop --require rubocop-sorbet --format offenses`

## RuboCop version

`1.21.0 (using Parser 3.0.2.0, rubocop-ast 1.11.0, running on ruby 2.7.3 x86_64-darwin20)`

**Comment by dvandersluis** [comment]
`rubocop-sorbet` is a shopify project, so you should probably file this issue in their repo.
