### ISSUE TITLE
Crash in Lint/RequireRelativeSelfPath

### ISSUE THREAD

**Issue by bpaquet** [rubocop/rubocop#10161]
--------

## Expected behavior

No error when parsing a Gemfile with
```
pre_commit_hook_installer = 'scripts/git_hooks/install_pre_commit_hook'
require_relative pre_commit_hook_installer
```

## Actual behavior

```
undefined method `value' for s(:lvar, :pre_commit_hook_installer):RuboCop::AST::Node
/Users/bpa/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rubocop-1.22.0/lib/rubocop/cop/lint/require_relative_self_path.rb:30:in `on_send'
/Users/bpa/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rubocop-1.22.0/lib/rubocop/cop/commissioner.rb:136:in `public_send'
```

## Steps to reproduce the problem

Create a Gemfile
```
pre_commit_hook_installer = 'scripts/git_hooks/install_pre_commit_hook'
require_relative pre_commit_hook_installer
```

rubocop -d Gemfile

## RuboCop version

```
1.22.0 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 3.0.2 x86_64-darwin20)
  - rubocop-performance 1.11.5
  - rubocop-rake 0.6.0
```

**Comment by koic** [comment]
This issue has been resolved by RuboCop 1.22.1. Can you update RuboCop to 1.22.1? Thank you.

**Comment by bpaquet** [comment]
Sorry for the noise.

**Comment by koic** [comment]
Never mind. Thank you for using the latest stable RuboCop!
