### ISSUE TITLE
Cop Style/CommentAnnotation errors on a simple comment

### ISSUE THREAD

**Issue by rtroch** [rubocop/rubocop#10190]
I have a simple file called `test.rb`:
```
# frozen_string_literal: true

class SomeClass
  def some_method
    puts 'some_text'
  end
end
```
In my `rubocop.yml` i have:
```
Style/CommentAnnotation:
  Keywords: TODO, FIXME, OPTIMIZE, HACK, REVIEW, REF
```
I run `bundle exec rubocop -d test.rb`:

## Expected behavior

Expected cop to pass without issues.

## Actual behavior

```
For /app: configuration from /app/.rubocop.yml
configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-performance-1.11.5/config/default.yml
configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-performance-1.11.5/config/default.yml
Default configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/config/default.yml
configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-rails-2.12.3/config/default.yml
configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-rails-2.12.3/config/default.yml
configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-rspec-2.5.0/config/default.yml
configuration from /usr/local/bundle/ruby/3.0.0/gems/rubocop-rspec-2.5.0/config/default.yml
Use parallel by default.
Running parallel inspection
An error occurred while Style/CommentAnnotation cop was inspecting /app/test.rb.
undefined method `sort_by' for "TODO, FIXME, OPTIMIZE, HACK, REVIEW, REF":String
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/mixin/annotation_comment.rb:45:in `split_comment'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/mixin/annotation_comment.rb:16:in `initialize'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:78:in `new'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:78:in `block in on_new_investigation'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:74:in `each'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:74:in `each_with_index'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:74:in `on_new_investigation'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `block (2 levels) in invoke'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `block in invoke'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `each'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `invoke'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:84:in `investigate'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/team.rb:83:in `investigate'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:309:in `inspect_file'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:253:in `block in do_inspection_loop'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:280:in `loop'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:130:in `block in file_offenses'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:155:in `file_offense_cache'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:129:in `file_offenses'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:67:in `block in warm_cache'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
/usr/local/bundle/ruby/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:238:in `each'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:67:in `warm_cache'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:46:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli.rb:71:in `run_command'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli.rb:78:in `execute_runners'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli.rb:47:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/exe/rubocop:12:in `block in <top (required)>'
/usr/local/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/exe/rubocop:12:in `<top (required)>'
/usr/local/bundle/ruby/3.0.0/bin/rubocop:23:in `load'
/usr/local/bundle/ruby/3.0.0/bin/rubocop:23:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:478:in `exec'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Inspecting 1 file
Scanning /app/test.rb
An error occurred while Style/CommentAnnotation cop was inspecting /app/test.rb.
undefined method `sort_by' for "TODO, FIXME, OPTIMIZE, HACK, REVIEW, REF":String
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/mixin/annotation_comment.rb:45:in `split_comment'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/mixin/annotation_comment.rb:16:in `initialize'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:78:in `new'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:78:in `block in on_new_investigation'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:74:in `each'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:74:in `each_with_index'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/style/comment_annotation.rb:74:in `on_new_investigation'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `block (2 levels) in invoke'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `block in invoke'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `each'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:153:in `invoke'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/commissioner.rb:84:in `investigate'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cop/team.rb:83:in `investigate'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:309:in `inspect_file'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:253:in `block in do_inspection_loop'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:280:in `loop'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:130:in `block in file_offenses'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:155:in `file_offense_cache'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:129:in `file_offenses'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:120:in `process_file'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:100:in `each'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:100:in `reduce'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:100:in `each_inspected_file'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:86:in `inspect_files'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/runner.rb:47:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli.rb:71:in `run_command'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli.rb:78:in `execute_runners'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/lib/rubocop/cli.rb:47:in `run'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/exe/rubocop:12:in `block in <top (required)>'
/usr/local/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/ruby/3.0.0/gems/rubocop-1.22.1/exe/rubocop:12:in `<top (required)>'
/usr/local/bundle/ruby/3.0.0/bin/rubocop:23:in `load'
/usr/local/bundle/ruby/3.0.0/bin/rubocop:23:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:478:in `exec'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/CommentAnnotation cop was inspecting /app/test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues
```
## Steps to reproduce the problem

Run the cop on the provided file.

## RuboCop version
```
1.22.1 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 3.0.2 aarch64-linux)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.12.3
  - rubocop-rspec 2.5.0

```

This has worked with rubocop 1.19 and fails with 1.22.

**Comment by tejasbubane** [comment]
@rtroch `Keywords` should be an array:

https://github.com/rubocop/rubocop/blob/25c95e6cb6c28a6a6ee259e9ba6dcc815ebb3f26/config/default.yml#L3205-L3211

**Comment by dvandersluis** [comment]
@tejasbubane is correct, YAML doesn't parse a CSV like you're giving it. Use a YAML array and all will work!
