### ISSUE TITLE
How can I inherit a config from the "rubocop" gem?

### ISSUE THREAD

**Issue by altjx** [rubocop/rubocop#10318]
While implementing Super-Linter, I noticed that it's inheriting from the `rubocop-github` gem, as shown here: https://github.com/github/super-linter/blob/main/TEMPLATES/.ruby-lint.yml

```
---
#######################
# Rubocop Config file #
#######################

inherit_gem:
  rubocop-github:
    - config/default.yml
```

However, the `rubocop-github` gem seems to be a bit dated, with recent updates from June 24th and a `default.yml` config file from over 2 years ago.

Ultimately, what I'm trying to do is inherit the rubocop gem and then overwrite some of the defaults. Here's what I have right now:

```
---

inherit_gem:
  rubocop-github:
    - config/default.yml

inherit_from:
  - https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
  - .rubocop-custom.yml
```

The problem with this is that `rubocop-github` gem (outdated) conflicts with my `rubocop` gem (more up-to-date). It would be great if I could do something like this:

```
# Common configuration.
---

inherit_gem:
  rubocop:
  - https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
 
inherit_from:
  - .rubocop-custom.yml
```

but this doesn't work.

_**EDIT**_

This seems to have done the trick:

```
# Common configuration.
---

inherit_gem:
  rubocop:
    - config/default.yml

inherit_from:
  - https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
  - .rubocop-custom.yml
```

However, after some extensive troubleshooting, I kept having issues inheriting the configuration from this gem because of the following line:

```
        if gem_name == 'rubocop'
          raise ArgumentError, "can't inherit configuration from the rubocop gem."
        end
```

located here: `/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/rubocop-1.24.0/lib/rubocop/config_loader_resolver.rb`

After commenting this out, everything worked flawlessly.

Any idea why this exists? I'm definitely not an expert in this, but I'm usually able to do some process of elimination to figure out the root cause. This seems to fix any issues I run into locally, but I guess my GitHub Action still fails because this exists in the original file on the runner.

```
can't inherit configuration from the rubocop gem
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader_resolver.rb:63:in `block in resolve_inheritance_from_gems'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader_resolver.rb:61:in `each_pair'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader_resolver.rb:61:in `resolve_inheritance_from_gems'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader.rb:50:in `load_file'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_store.rb:29:in `options_config='
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/cli.rb:90:in `act_on_options'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/cli.rb:38:in `run'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/exe/rubocop:12:in `block in <top (required)>'
/usr/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/exe/rubocop:12:in `<top (required)>'
/usr/bin/rubocop:25:in `load'
/usr/bin/rubocop:25:in `<main>'
```

**Comment by altjx** [comment]
Fixed:

```
# Common configuration.
---

inherit_from:
  - https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
  - .rubocop-custom.yml
```
