### ISSUE TITLE
Infinite loop detected in /Users/robert/gh/lab42/tmp/example.rb and caused by Layout/IndentationConsistency -> Layout/IndentationWidth

### ISSUE THREAD

**Issue by RobertDober** [rubocop/rubocop#10396]
## Expected behavior

Autocorect

## Actual behavior
Crash

## Steps to reproduce the problem
```sh
rubocop --debug example.rb -A                                                                                                                                     [9:23:54]
For /Users/robert/gh/lab42/tmp: configuration from /Users/robert/gh/lab42/tmp/.rubocop.yml
Default configuration from /Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/config/default.yml
Inspecting 1 file
Scanning /Users/robert/gh/lab42/tmp/example.rb
C

Offenses:

example.rb:6:3: C: [Corrected] Layout/IndentationWidth: Use 2 (not 16) spaces for indentation.
                  def color_value(color_spec)
  ^^^^^^^^^^^^^^^^
example.rb:6:5: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
    def color_value(color_spec) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /Users/robert/gh/lab42/tmp/example.rb and caused by Layout/IndentationConsistency -> Layout/IndentationWidth
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:298:in `check_for_infinite_loop'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:281:in `block in iterate_until_no_changes'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:280:in `loop'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:130:in `block in file_offenses'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:155:in `file_offense_cache'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:129:in `file_offenses'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:120:in `process_file'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:100:in `each'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:100:in `reduce'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/runner.rb:47:in `run'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli/command.rb:11:in `run'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli/environment.rb:18:in `run'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli.rb:71:in `run_command'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cli.rb:47:in `run'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/exe/rubocop:12:in `block in <top (required)>'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/robert/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/exe/rubocop:12:in `<top (required)>'
/Users/robert/.asdf/installs/ruby/3.1.0/bin/rubocop:25:in `load'
/Users/robert/.asdf/installs/ruby/3.1.0/bin/rubocop:25:in `<main>'
```
## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
rubocop -V                                                                                                                                                        [9:27:10]
1.25.1 (using Parser 3.1.0.0, rubocop-ast 1.15.1, running on ruby 3.1.0 x86_64-darwin21)
```
[resources.zip](https://github.com/rubocop/rubocop/files/7992934/resources.zip)

**Comment by RobertDober** [comment]
Oh here is the state of the partially corrected file when rubocop crashes

```ruby
# frozen_string_literal: true

require_relative "tag_cloud/compiler"

module Lab42
  module TagCloud extend self
                  def color_value(color_spec)
                    Compiler.color_value(color_spec.to_s)
                  end
  end
end
#  SPDX-License-Identifier: Apache-2.0
```

**Comment by RobertDober** [comment]
after some tinkering I found out that the `extend self` in the same line as `module` triggers this exception

**Comment by johnny-miyake** [comment]
I reproduced this problem disabling [Style/TrailingBodyOnModule](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingBodyOnModule).

The code to reproduce.
```ruby
module Foo extend Bar
  something
end

# Got this error:
# Infinite loop detected in /path/to/example.rb and caused by Layout/IndentationConsistency -> Layout/IndentationWidth
```

The autocorrect works with no errors when `Style/TrailingBodyOnModule` is enabled.
```ruby
module Foo
  extend Bar
  something
end
```

Should we fix this problem so that this cop's autocorrect works whether `Style/TrailingBodyOnModule` is enabled?
