### ISSUE TITLE
Unsafe autocorrect for `Style/FileWrite` with splat arguments

### ISSUE THREAD

**Issue by msbit** [rubocop/rubocop#10468]
Rubocop doesn't safely autocorrect the following following construct:

```
data = [1, 2, 3, 4, "\n"]

File.open('output', 'w') do |f|
  f.write(*data)
end
```

using the `*` operator to pass the arguments to `File#write`.

## Expected behavior

In this case, probably to leave that construct alone when safely autocorrecting. It would seem a pretty acceptable candidate for unsafe autocorrection though.

## Actual behavior

Rubocop corrects this to:

```
# frozen_string_literal: true

data = [1, 2, 3, 4, "\n"]

File.write('output', *data)
```

which, when run, gives the following error:

```
Traceback (most recent call last):
	1: from test.rb:5:in `<main>'
test.rb:5:in `write': wrong number of arguments (given 6, expected 2..3) (ArgumentError)
```

## Steps to reproduce the problem

```
$ cat test.rb
# frozen_string_literal: true

data = [1, 2, 3, 4, "\n"]

File.open('output', 'w') do |f|
  f.write(*data)
end

$ ruby test.rb

$ cat output
1234

$ cat .rubocop.yml 
AllCops:
  NewCops: enable

$ rubocop --auto-correct --debug test.rb
For /Users/tom/Development/msbit/rubocop-style-file-write: configuration from /Users/tom/Development/msbit/rubocop-style-file-write/.rubocop.yml
Default configuration from /Users/tom/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rubocop-1.26.1/config/default.yml
Inspecting 1 file
Scanning /Users/tom/Development/msbit/rubocop-style-file-write/test.rb
C

Offenses:

test.rb:5:1: C: [Corrected] Style/FileWrite: Use File.write.
File.open('output', 'w') do |f| ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
Finished in 0.2429499999852851 seconds

$ ruby test.rb
Traceback (most recent call last):
	1: from test.rb:5:in `<main>'
test.rb:5:in `write': wrong number of arguments (given 6, expected 2..3) (ArgumentError)
```

## RuboCop version

```
$ rubocop --debug -V
For /Users/tom/Development/msbit/rubocop-style-file-write: configuration from /Users/tom/Development/msbit/rubocop-style-file-write/.rubocop.yml
Default configuration from /Users/tom/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rubocop-1.26.1/config/default.yml
1.26.1 (using Parser 3.1.1.0, rubocop-ast 1.16.0, running on ruby 2.7.4 x86_64-darwin18)
Finished in 0.12169099994935095 seconds
```

**Comment by msbit** [comment]
👍🏻
