### ISSUE TITLE
`--stderr` cause hang after `--start-server`

### ISSUE THREAD

**Issue by marocchino** [rubocop/rubocop#11034]
## Expected behavior

I want rubocop to return an appropriate return value regardless of whether the option is used or not.
## Actual behavior

I found that running lint with the --stderr option keeps waiting command  after running the server.

## Steps to reproduce the problem

Gemfile
```rb
gem 'rubocop'
```

Gemfile.lock
```
GEM
  specs:
    ast (2.4.2)
    json (2.6.2)
    parallel (1.22.1)
    parser (3.1.2.1)
      ast (~> 2.4.1)
    rainbow (3.1.1)
    regexp_parser (2.6.0)
    rexml (3.2.5)
    rubocop (1.36.0)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.1.2.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.20.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.21.0)
      parser (>= 3.1.1.0)
    ruby-progressbar (1.11.0)
    unicode-display_width (2.3.0)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  rubocop

BUNDLED WITH
   2.3.9
```

```bash
$ bundle exec rubocop --stderr Gemfile
Inspecting 1 file
C

Offenses:

Gemfile:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
gem 'rubocop'
^

1 file inspected, 1 offense detected, 1 offense autocorrectable
# no problem here
$ bundle exec rubocop --start-server
RuboCop server starting on 127.0.0.1:64066.
$ bundle exec rubocop --stderr Gemfile --debug
For /Users/marocchino/Documents/rubocop-hang: Inspecting 1 file
Scanning /Users/marocchino/Documents/rubocop-hang/Gemfile
Loading cache from /Users/marocchino/.cache/rubocop_cache/befc449a3d70337f61a0fe7788be8a28284d0caa/f9987d68d252fab787d9f5979625bc941c247b33/3a85b4f6596126525b1f00421461c9f61b40fe85
C

Offenses:

Gemfile:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
gem 'rubocop'
^

1 file inspected, 1 offense detected, 1 offense autocorrectable
# hanging here and never return..
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2) +server [arm64-darwin21]
```

**Comment by marocchino** [comment]
Additionally, when I force quit, I get this stack trace like this:
```
^C/Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/server/client_command/base.rb:32:in `eof?': Interrupt
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/server/client_command/base.rb:32:in `block in send_request'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/server/client_command/base.rb:28:in `open'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/server/client_command/base.rb:28:in `send_request'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/server/client_command/exec.rb:21:in `run'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/exe/rubocop:12:in `<top (required)>'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/bin/rubocop:25:in `load'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/bin/rubocop:25:in `<top (required)>'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
	from /Users/marocchino/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'

```
