### ISSUE TITLE
`Lint/RedundantCopDisableDirective` crashes when disabling `Rails` department

### ISSUE THREAD

**Issue by ojab** [rubocop/rubocop#11147]
When using Rails project with not-only-rails parts, it's desirable to disable all the Rails cops, and with comment: 
```ruby
# rubocop:disable Rails
```

## Expected behavior

It works!

## Actual behavior

```
$ rubocop -rrubocop-rails -d -o Lint/RedundantCopDisableDirective r.rb 
For /tmp: Scanning /tmp/r.rb
An error occurred while Lint/RedundantCopDisableDirective cop was inspecting /tmp/r.rb.
Couldn't find Rails/ActionControllerFlashBeforeRender in comment: # rubocop:disable Rails
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:256:in `cop_range'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:233:in `block in add_offense_for_some_cops'
/home/ojab/.rbenv/versions/3.1.2/lib/ruby/3.1.0/set.rb:511:in `each_key'
/home/ojab/.rbenv/versions/3.1.2/lib/ruby/3.1.0/set.rb:511:in `each'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:233:in `map'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:233:in `add_offense_for_some_cops'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:212:in `block in add_offenses'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:208:in `each'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:208:in `add_offenses'
.../rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:51:in `on_new_investigation'
.../rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `block (2 levels) in invoke'
.../rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
.../rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `block in invoke'
.../rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `each'
.../rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `invoke'
.../rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:84:in `investigate'
.../rubocop-1.38.0/lib/rubocop/cop/team.rb:154:in `investigate_partial'
.../rubocop-1.38.0/lib/rubocop/cop/team.rb:82:in `investigate'
.../rubocop-1.38.0/lib/rubocop/runner.rb:315:in `inspect_file'
.../rubocop-1.38.0/lib/rubocop/runner.rb:172:in `block in add_redundant_disables'
.../rubocop-1.38.0/lib/rubocop/runner.rb:193:in `team_for_redundant_disables'
.../rubocop-1.38.0/lib/rubocop/runner.rb:171:in `add_redundant_disables'
.../rubocop-1.38.0/lib/rubocop/runner.rb:139:in `block in file_offenses'
.../rubocop-1.38.0/lib/rubocop/runner.rb:163:in `file_offense_cache'
.../rubocop-1.38.0/lib/rubocop/runner.rb:137:in `file_offenses'
.../rubocop-1.38.0/lib/rubocop/runner.rb:128:in `process_file'
.../rubocop-1.38.0/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
.../rubocop-1.38.0/lib/rubocop/runner.rb:108:in `each'
.../rubocop-1.38.0/lib/rubocop/runner.rb:108:in `reduce'
.../rubocop-1.38.0/lib/rubocop/runner.rb:108:in `each_inspected_file'
.../rubocop-1.38.0/lib/rubocop/runner.rb:94:in `inspect_files'
.../rubocop-1.38.0/lib/rubocop/runner.rb:47:in `run'
.../rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
.../rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
.../rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
.../rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
.../rubocop-1.38.0/lib/rubocop/cli/command.rb:11:in `run'
.../rubocop-1.38.0/lib/rubocop/cli/environment.rb:18:in `run'
.../rubocop-1.38.0/lib/rubocop/cli.rb:72:in `run_command'
.../rubocop-1.38.0/lib/rubocop/cli.rb:79:in `execute_runners'
.../rubocop-1.38.0/lib/rubocop/cli.rb:48:in `run'
.../rubocop-1.38.0/exe/rubocop:19:in `block in <top (required)>'
/home/ojab/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
.../rubocop-1.38.0/exe/rubocop:19:in `<top (required)>'
/home/ojab/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
/home/ojab/.rbenv/versions/3.1.2/bin/rubocop:25:in `<main>'

1 error occurred:
An error occurred while Lint/RedundantCopDisableDirective cop was inspecting /tmp/r.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues
```

## Steps to reproduce the problem

Above.

## RuboCop version

```
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-linux]
  - rubocop-rails 2.17.2
```

**Comment by koic** [comment]
This issue may be the same as #11143.

**Comment by ojab** [comment]
yep, looks like a duplicate
