### ISSUE TITLE
An error occurred while Style/RedundantCurrentDirectoryInPath cop was inspecting

### ISSUE THREAD

**Issue by HoneyryderChuck** [rubocop/rubocop#11980]
## Expected behavior

Been using rubocop in `httpx` always targeting latest, and it [started failing today](https://gitlab.com/os85/httpx/-/jobs/4534730175).

## Actual behavior

```
> bundle exec rubocop -a lib/httpx/plugins/proxy.rb -d
For /home/dev/httpx: configuration from /home/dev/httpx/.rubocop.yml
configuration from /home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-performance-1.18.0/config/default.yml
configuration from /home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-performance-1.18.0/config/default.yml
Default configuration from /home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/config/default.yml
Inheriting configuration from /home/dev/httpx/.rubocop_todo.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /home/dev/httpx/lib/httpx/plugins/proxy.rb
An error occurred while Style/RedundantCurrentDirectoryInPath cop was inspecting /home/dev/httpx/lib/httpx/plugins/proxy.rb:81:10.
undefined method `start_with?' for nil:NilClass
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/style/redundant_current_directory_in_path.rb:25:in `on_send'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:107:in `public_send'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:107:in `block (2 levels) in trigger_responding_cops'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:106:in `block in trigger_responding_cops'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:105:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:105:in `trigger_responding_cops'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:157:in `on_if'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:154:in `on_def'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_def'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'                                                                             [56/1807]
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:154:in `on_class'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:138:in `on_while'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:138:in `on_while'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:138:in `on_while'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cop/team.rb:91:in `investigate'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:344:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:344:in `flat_map'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:344:in `inspect_file'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:314:in `loop'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:314:in `loop'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:163:in `file_offenses'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:154:in `process_file'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:134:in `each'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:134:in `reduce'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:120:in `inspect_files'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/runner.rb:73:in `run'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli/command.rb:11:in `run'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli.rb:118:in `run_command'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli.rb:125:in `execute_runners'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli.rb:51:in `block in run'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/lib/rubocop/cli.rb:43:in `run'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/exe/rubocop:19:in `block in <top (required)>'
/home/.rubies/ruby-3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/dev/httpx/.bundle/ruby/3.2.0/gems/rubocop-1.53.0/exe/rubocop:19:in `<top (required)>'
/home/dev/httpx/.bundle/ruby/3.2.0/bin/rubocop:25:in `load'
/home/dev/httpx/.bundle/ruby/3.2.0/bin/rubocop:25:in `<top (required)>'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/.gem/ruby/3.2.2/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/home/.gem/ruby/3.2.2/bin/bundle:25:in `load'
/home/.gem/ruby/3.2.2/bin/bundle:25:in `<main>'
```

## Steps to reproduce the problem

Run the specified command with the prompt above in [httpx master branch](https://gitlab.com/os85/httpx).

## RuboCop version

```
 > bundle exec rubocop -V
1.53.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-darwin21]
  - rubocop-performance 1.18.0
```

**Comment by koic** [comment]
This issue is a dup with https://github.com/rubocop/rubocop/pull/11974 and fixed by https://github.com/rubocop/rubocop/pull/11975.
