### ISSUE TITLE
Upgrade to 1.54 => Metrics/Blocklength Cop + Heredoc throws error

### ISSUE THREAD

**Issue by serioushaircut** [rubocop/rubocop#12023]
Hi dear rubocop lovers

on upgrading to 1.54 we experienced the following error while rubocop evaluated the Metrics/Blocklength cop.

## Expected behavior

there is not an error and rubocop Metrics/Blocklength cop either reports violations or doesn't.

## Actual behavior

On running rubcop we see a bunch of errors 
`An error occurred while Metrics/BlockLength cop was inspecting /home/spin/src/github.com/Shopify/business-platform/rubocop_heredoc_blocklength.rb:2:2.` and rubocop exits with an error code.

Here's a stacktrace from rubcop -d with the minimal sample file given below
```
...
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /home/spin/src/github.com/Shopify/business-platform/rubocop_heredoc_blocklength.rb

An error occurred while Metrics/BlockLength cop was inspecting /home/spin/src/github.com/Shopify/business-platform/rubocop_heredoc_blocklength.rb:2:2.       # ! <----
undefined method `last_line' for nil:NilClass             # ! <----

/home/spin/.bundle/business-platform/gems/parser-3.2.2.3/lib/parser/source/map.rb:118:in `last_line'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node.rb:266:in `last_line'
/home/spin/.bundle/business-platform/gems/rubocop-1.54.0/lib/rubocop/cop/metrics/utils/code_length_calculator.rb:200:in `block in source_from_node_with_heredoc'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:111:in `block in visit_descendants'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:108:in `each'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:108:in `visit_descendants'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:112:in `block in visit_descendants'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:108:in `each'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:108:in `visit_descendants'
/home/spin/.bundle/business-platform/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:63:in `each_descendant'
/home/spin/.bundle/business-platform/gems/rubocop-1.54.0/lib/rubocop/cop/metrics/utils/code_length_calculator.rb:192:in `source_from_node_with_heredoc'
/home/spin/.bundle/business-platform/gems/rubocop-1.54.0/lib/rubocop/cop/metrics/utils/code_length_calculator.rb:77:in `code_length'
/home/spin/.bundle/business-platform/gems/rubocop-1.54.0/lib/rubocop/cop/metrics/utils/code_length_calculator.rb:25:in `calculate'
/home/spin/.bundle/business-platform/gems/rubocop-1.54.0/lib/rubocop/cop/mixin/code_length.rb:36:in `check_code_length'
/home/spin/.bundle/business-platform/gems/rubocop-1.54.0/lib/rubocop/cop/metrics/block_length.rb:56:in `on_block'
...
```

## Steps to reproduce the problem
I created a somewhat minimal file to trigger the error and to play around with the conditions on when it hits:
```
module FooBar
  [].map do |_a| # something with a block
    desc <<~EOS
      a heredoc block is necessary !!!
    EOS
    # 4
    # 5
    # 6
    # 7
    # 8
    # 9
    # 10
    [].map {} # something with *another block*, `p 1` or so does not trigger error
  end
end
```
This triggers the error if:
- the cop can detect a violation (here blocklength > 10
- there is a block with a heredoc 
- the block contains at least another block

## RuboCop version
```
✗1 ~/... dependabot/bundler/rubocop-1.54.0 % bundle e rubocop -V  business-platform-with-payment-service-ae3x
1.54.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-graphql 1.3.0
  - rubocop-performance 1.18.0
  - rubocop-rails 2.20.2
  - rubocop-rspec 2.22.0
  - rubocop-sorbet 0.7.0
```

**Comment by koic** [comment]
This issue is a dup with https://github.com/rubocop/rubocop/issues/12013 and fixed by https://github.com/rubocop/rubocop/pull/12011. Thank you.
