### ISSUE TITLE
undefined method `type` for `nil:NilClass`

### ISSUE THREAD

**Issue by snutij** [rubocop/rubocop#12198]
Hello, not sure, if the best place to open an issue is here, or maybe it's more related to `rubocop-ast`. Feel free to redirect me 🙏 

Given a file `foo.rb`:

```ruby
if ..1 ; end
```

OR 

```ruby
if 1.. ; end
```

Which is a valid syntax with warning: 

```
ruby -c foo.rb
foo.rb:1: warning: integer literal in flip-flop
Syntax OK
```

--------

## Expected behavior

Should be able to parse the file, without crashing. 

## Actual behavior

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

```
bin/rubocop -d foo.rb
[...]

0 files inspected, no offenses detected
undefined method `type' for nil:NilClass
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1676:in `check_condition'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1706:in `check_condition'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1275:in `condition'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/ruby30.rb:9854:in `_reduce_329'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/racc-1.7.1/lib/racc/parser.rb:265:in `_racc_do_parse_c'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/racc-1.7.1/lib/racc/parser.rb:265:in `do_parse'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/base.rb:190:in `parse'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/base.rb:238:in `tokenize'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:215:in `tokenize'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:210:in `parse'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:38:in `initialize'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:23:in `new'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:23:in `from_file'
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.56.2/lib/rubocop/runner.rb:478:in `get_processed_source'
```

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

```bash
bundle exec rubocop -V

1.56.2 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [arm64-darwin22]
  - rubocop-minitest 0.31.1
  - rubocop-rake 0.6.0
  - rubocop-sorbet 0.7.3
```

**Comment by snutij** [comment]
For the record, this is clearly something related to the `Parser` gem used.

With a file `foo.rb`

```ruby
if 1.. ; end
```

```
ruby-parse foo.rb
Failed on: foo.rb
/Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1676:in `check_condition': undefined method `type' for nil:NilClass (NoMethodError)

      case cond.type
               ^^^^^
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1707:in `check_condition'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1275:in `condition'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/ruby32.rb:10270:in `_reduce_338'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/racc-1.7.1/lib/racc/parser.rb:265:in `_racc_do_parse_c'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/racc-1.7.1/lib/racc/parser.rb:265:in `do_parse'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/base.rb:190:in `parse'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner/ruby_parse.rb:141:in `process'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:259:in `process_buffer'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:252:in `block in process_files'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:241:in `each'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:241:in `process_files'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:221:in `block in process_all_input'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:219:in `process_all_input'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner/ruby_parse.rb:137:in `process_all_input'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:35:in `execute'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/runner.rb:13:in `go'
	from /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/bin/ruby-parse:7:in `<top (required)>'
	from /Users/snutij/.rbenv/versions/3.2.2/bin/ruby-parse:25:in `load'
	from /Users/snutij/.rbenv/versions/3.2.2/bin/ruby-parse:25:in `<main>'
```

It failed here: https://github.com/whitequark/parser/blob/master/lib/parser/builders/default.rb#L1676

Where:

```ruby
# first time
(rdbg) cond
s(:irange,
  s(:int, 1), nil)
(ruby) cond.type
:irange

# second time
(rdbg) cond
s(:int, 1)
(ruby) cond.type
:int

# third time
(rdbg) cond
nil
(ruby) cond.type
eval error: undefined method `type' for nil:NilClass
  (rdbg)//Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1:in `check_condition'
nil
```

On Rubocop side, it's failed when file is parsed: 

https://github.com/rubocop/rubocop/blob/9fdc532bc8c448c43dab537cbf7949370bb58f68/lib/rubocop/runner.rb#L474-L482

```ruby
(ruby) @options[:stdin]
"if 1.. ; end\n"

(ruby) ruby_version
3.0

(ruby) ProcessedSource.new(@options[:stdin], ruby_version, file)
eval error: undefined method `type' for nil:NilClass
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1676:in `check_condition'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1707:in `check_condition'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1275:in `condition'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/ruby30.rb:9854:in `_reduce_329'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/racc-1.7.1/lib/racc/parser.rb:265:in `_racc_do_parse_c'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/racc-1.7.1/lib/racc/parser.rb:265:in `do_parse'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/base.rb:190:in `parse'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/base.rb:238:in `tokenize'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:215:in `tokenize'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:210:in `parse'
  /Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/processed_source.rb:38:in `initialize'
  (rdbg)//Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:1:in `new'
  (rdbg)//Users/snutij/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:1:in `get_processed_source'
nil
```

Do not hesitate if you need anything else 🙏
