### ISSUE TITLE
Error running on heroku CI

### ISSUE THREAD

**Issue by m5rk** [rubocop/rubocop#12533]
I am trying to run rubocop on heroku CI using this command in the environments.test.scripts section of app.json:

```
      "scripts": {
        "test-setup": "bundle exec rubocop --require rubocop-rails --require rubocop-rspec --require rubocop-factory_bot",
        "test": "bundle exec rake 'knapsack:rspec[--tag ~type:feature --tag ~@perf]'"
      }

```

I installed the following gems in :development and :test:

```
group :development, :test do
  gem 'rubocop'
  gem 'rubocop-factory_bot'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  ...
```

On the test run, I see this error:

```
Running RuboCop...
cannot load such file -- standard
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/feature_loader.rb:39:in `rescue in load'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/feature_loader.rb:32:in `load'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/feature_loader.rb:21:in `load'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_loader_resolver.rb:13:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
<internal:kernel>:90:in `tap'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_loader.rb:53:in `load_file'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_loader.rb:112:in `configuration_from_file'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_store.rb:68:in `for_dir'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/config_store.rb:58:in `for'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:165:in `ruby_interpreters'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:157:in `ruby_executable?'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:173:in `ruby_file?'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:73:in `to_inspect?'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:64:in `block in target_files_in_dir'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:64:in `select'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/target_finder.rb:32:in `find'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/runner.rb:111:in `find_target_files'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/runner.rb:68:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli/command.rb:11:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli/environment.rb:18:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli.rb:118:in `run_command'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli.rb:125:in `execute_runners'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli.rb:51:in `block in run'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/cli.rb:43:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/rake_task.rb:51:in `run_cli'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/rake_task.rb:26:in `block (2 levels) in initialize'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/file_utils_ext.rb:58:in `verbose'
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/rake_task.rb:24:in `block in initialize'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/3.1.0/gems/airbrake-13.0.3/lib/airbrake/rake.rb:17:in `execute'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/3.1.0/bin/rake:25:in `load'
/app/vendor/bundle/ruby/3.1.0/bin/rake:25:in `<top (required)>'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
/app/vendor/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
/app/vendor/ruby-3.1.4/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/app/vendor/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
/app/bin/bundle:104:in `load'
/app/bin/bundle:104:in `<main>'
RuboCop failed!
-----> test-setup command `bundle exec rake rubocop` failed with exit status 1
```

## Expected behavior

I expect to see the same output that I see when running rubocop locally.

## Actual behavior

I see the stacktrace posted above.

## Steps to reproduce the problem

Push a commit the branch where I'm trying to introduce rubocop to my app. That triggers CI.

## RuboCop version

```
$ bundle exec rubocop -V
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.1.4) [x86_64-darwin22]
  - rubocop-factory_bot 2.24.0
  - rubocop-rails 2.22.2
  - rubocop-rspec 2.25.0
```

**Comment by mediazard** [comment]
try to add gem 'standard' to your dev/test group

**Comment by m5rk** [comment]
> try to add `gem 'standard'` to your dev/test group

That helped reveal the next error. But why isn't that mentioned in the README or included as a dependency when installing rubocop?

I also had to add 'rubocop-rake' to my Gemfile even though I don't have that extension listed in .rubocop.yml.

And then after adding that to my Gemfile, I get to the next error, which is very puzzling:

```
-----> Running test-setup command `bundle exec rubocop`...
vendor/bundle/ruby/3.1.0/gems/draper-4.0.2/.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
Please also note that you can opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true
Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
Lint/DuplicateBranch: # new in 1.3
  Enabled: true
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true
Lint/EmptyBlock: # new in 1.1
  Enabled: true
Lint/EmptyClass: # new in 1.3
  Enabled: true
Lint/EmptyInPattern: # new in 1.16
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true
Lint/MixedCaseRange: # new in 1.53
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true
Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/SymbolConversion: # new in 1.9
  Enabled: true
Lint/ToEnumArguments: # new in 1.1
  Enabled: true
Lint/TripleQuotes: # new in 1.9
  Enabled: true
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true
Lint/UselessRescue: # new in 1.43
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/ArgumentsForwarding: # new in 1.1
  Enabled: true
Style/ArrayIntersect: # new in 1.40
  Enabled: true
Style/CollectionCompact: # new in 1.2
  Enabled: true
Style/ComparableClamp: # new in 1.44
  Enabled: true
Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true
Style/DataInheritance: # new in 1.49
  Enabled: true
Style/DirEmpty: # new in 1.48
  Enabled: true
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true
Style/EmptyHeredoc: # new in 1.32
  Enabled: true
Style/EndlessMethod: # new in 1.8
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/ExactRegexpMatch: # new in 1.51
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/FileEmpty: # new in 1.48
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: true
Style/HashConversion: # new in 1.10
  Enabled: true
Style/HashExcept: # new in 1.7
  Enabled: true
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true
Style/InPatternThen: # new in 1.16
  Enabled: true
Style/MagicCommentFormat: # new in 1.35
  Enabled: true
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true
Style/MapToHash: # new in 1.24
  Enabled: true
Style/MapToSet: # new in 1.42
  Enabled: true
Style/MinMaxComparison: # new in 1.42
  Enabled: true
Style/MultilineInPatternThen: # new in 1.16
  Enabled: true
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true
Style/NestedFileDirname: # new in 1.26
  Enabled: true
Style/NilLambda: # new in 1.3
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: true
Style/OperatorMethodCall: # new in 1.37
  Enabled: true
Style/QuotedSymbols: # new in 1.16
  Enabled: true
Style/RedundantArgument: # new in 1.4
  Enabled: true
Style/RedundantArrayConstructor: # new in 1.52
  Enabled: true
Style/RedundantConstantBase: # new in 1.40
  Enabled: true
Style/RedundantCurrentDirectoryInPath: # new in 1.53
  Enabled: true
Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true
Style/RedundantEach: # new in 1.38
  Enabled: true
Style/RedundantFilterChain: # new in 1.52
  Enabled: true
Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Style/RedundantLineContinuation: # new in 1.49
  Enabled: true
Style/RedundantRegexpArgument: # new in 1.53
  Enabled: true
Style/RedundantRegexpConstructor: # new in 1.52
  Enabled: true
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/RedundantStringEscape: # new in 1.37
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition: # new in 1.53
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
Style/SingleLineDoEndBlock: # new in 1.57
  Enabled: true
Style/StringChars: # new in 1.12
  Enabled: true
Style/SwapValues: # new in 1.1
  Enabled: true
Style/YAMLFileRead: # new in 1.53
  Enabled: true
FactoryBot/AssociationStyle: # new in 2.23
  Enabled: true
FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy: # new in 2.23
  Enabled: true
FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true
FactoryBot/IdSequence: # new in <<next>>
  Enabled: true
FactoryBot/RedundantFactoryOption: # new in 2.23
  Enabled: true
FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: true
Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: true
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/ActionOrder: # new in 2.17
  Enabled: true
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: true
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: true
Rails/AddColumnIndex: # new in 2.11
  Enabled: true
Rails/AfterCommitOverride: # new in 2.8
  Enabled: true
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DangerousColumnNames: # new in 2.21
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: true
Rails/EnvLocal: # new in 2.22
  Enabled: true
Rails/ExpandedDateRange: # new in 2.11
  Enabled: true
Rails/FindById: # new in 2.7
  Enabled: true
Rails/FreezeTime: # new in 2.16
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: true
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: true
Rails/Inquiry: # new in 2.7
  Enabled: true
Rails/MailerName: # new in 2.7
  Enabled: true
Rails/MatchRoute: # new in 2.7
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/NegateInclude: # new in 2.7
  Enabled: true
Rails/Pluck: # new in 2.7
  Enabled: true
Rails/PluckInWhere: # new in 2.7
  Enabled: true
Rails/RedundantActiveRecordAllMethod: # new in 2.21
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/RenderInline: # new in 2.7
  Enabled: true
Rails/RenderPlainText: # new in 2.7
  Enabled: true
Rails/ResponseParsedBody: # new in 2.18
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/RootPathnameMethods: # new in 2.16
  Enabled: true
Rails/RootPublicPath: # new in 2.15
  Enabled: true
Rails/SelectMap: # new in 2.21
  Enabled: true
Rails/ShortI18n: # new in 2.7
  Enabled: true
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: true
Rails/StripHeredoc: # new in 2.15
  Enabled: true
Rails/ThreeStateBooleanColumn: # new in 2.19
  Enabled: true
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: true
Rails/ToFormattedS: # new in 2.15
  Enabled: true
Rails/ToSWithArgument: # new in 2.16
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: true
Rails/UnusedRenderContent: # new in 2.21
  Enabled: true
Rails/WhereEquals: # new in 2.9
  Enabled: true
Rails/WhereExists: # new in 2.7
  Enabled: true
Rails/WhereMissing: # new in 2.16
  Enabled: true
Rails/WhereNot: # new in 2.8
  Enabled: true
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: true
Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: true
Capybara/MatchStyle: # new in 2.17
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: true
Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: true
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: true
RSpec/MatchArray: # new in 2.19
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: true
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: true
RSpec/Rails/MinitestAssertions: # new in 2.17
  Enabled: true
RSpec/Rails/NegationBeValid: # new in 2.23
  Enabled: true
RSpec/Rails/TravelAround: # new in 2.19
  Enabled: true
Performance/AncestorsInclude: # new in 1.7
  Enabled: true
Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true
Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true
Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true
Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: true
Performance/ConstantRegexp: # new in 1.9
  Enabled: true
Performance/MapCompact: # new in 1.11
  Enabled: true
Performance/MapMethodChain: # new in 1.19
  Enabled: true
Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: true
Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true
Performance/RedundantSortBlock: # new in 1.7
  Enabled: true
Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true
Performance/RedundantStringChars: # new in 1.7
  Enabled: true
Performance/ReverseFirst: # new in 1.7
  Enabled: true
Performance/SortReverse: # new in 1.7
  Enabled: true
Performance/Squeeze: # new in 1.7
  Enabled: true
Performance/StringIdentifierArgument: # new in 1.13
  Enabled: true
Performance/StringInclude: # new in 1.7
  Enabled: true
Performance/Sum: # new in 1.8
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
vendor/bundle/ruby/3.1.0/gems/dry-container-0.7.2/.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
vendor/bundle/ruby/3.1.0/gems/dry-container-0.7.2/.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
Error: The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in vendor/bundle/ruby/3.1.0/gems/dry-container-0.7.2/.rubocop.yml, please update it)
-----> test-setup command `bundle exec rubocop` failed with exit status 2
```

It appears to be including the .rubocop.yml files from the gems in my Gemfile? That's completely surprising.

**Comment by m5rk** [comment]
And, these errors do not happen locally.

**Comment by dvandersluis** [comment]
`standard` isn’t a dependency of rubocop, what in your gemfile is pulling it in, if you’re not doing so directly?

**Comment by m5rk** [comment]
The error about standard only occurs for me on heroku CI and it occurs in the rubocop feature loader as I noted above:

```
Running RuboCop...
cannot load such file -- standard
/app/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue i
```

**Comment by m5rk** [comment]
I added `vendor/**/*` to the exclude list and that enabled me to finally got rubocop to run on heroku CI. This makes sense as an issue with heroku CI. The included gems end up in vendor, which isn't true locally.

Here's my resulting .rubocop.yml:

```
require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - client/node_modules/**/*
    - node_modules/**/*
    - spec/features/**/*
    - vendor/**/*
```

Enduring surprises that I don't understand:

1. The issue with the standard gem, that only occurs on heroku CI. Workaround: Add to Gemfile.
2. The issue with rubocop-rake, that only occurs on heroku CI. Workaround: Add to Gemfile.

**Comment by dvandersluis** [comment]
My guess is that something that you're loading has its own rubocop config that uses standard (standard depends on rubocop, not the other way around), that is getting pulled in. If you remove `standard` from your Gemfile after excluding `vendor` does it error again?

**Comment by m5rk** [comment]
> My guess is that something that you're loading has its own rubocop config that uses standard (standard depends on rubocop, not the other way around), that is getting pulled in. If you remove `standard` from your Gemfile after excluding `vendor` does it error again?

Good point. Yes, the true fix was to exclude vendor on heroku CI. That allowed me to remove the unnecessary dependency on standard and rubocop-rake. It was the unintentional inclusion of vendor that triggered those.

Has no one else tried to run rubocop on heroku CI? I'm surprised I'm the first one to encounter this issue. And the fix is simple: Add `vendor/**/*` to the list of excluded files in .rubocop.yml.

**Comment by m5rk** [comment]
For me, this issue is resolved: To run rubocop on heroku CI, make sure you exclude vendor:

```
# .rubocop.yml
AllCops:
  Exclude:
    - vendor/**/*
```

**Comment by dvandersluis** [comment]
I think it's come up in issues before about vendored gems. `vendor/**/*` is [excluded in the default rubocop config](https://github.com/rubocop/rubocop/blob/e5a164a26f8ecba81d44e974e8e3569c550968cd/config/default.yml#L65-L69) but if your `.rubocop.yml` has its own `Exclude` you're probably clobbering that.

See https://docs.rubocop.org/rubocop/1.59/configuration.html#inheritance - you may need to add 

```yaml
inherit_mode:
  merge:
  - Exclude
```

**Comment by m5rk** [comment]
Thanks, I was not inheriting Exclude. I'll make that change.
