### ISSUE TITLE
Infinite loop detected in /a.rb and caused by Style/ArgumentsForwarding

### ISSUE THREAD

**Issue by znz** [rubocop/rubocop#12629]
Steps at https://github.com/rubocop/rubocop/issues/12619#issuecomment-1893142894 cause `Infinite loop detected in /a.rb and caused by Style/ArgumentsForwarding`.

--------

## Expected behavior

No errors.

## Actual behavior

rubocop says `Infinite loop detected in /a.rb and caused by Style/ArgumentsForwarding`.

## Steps to reproduce the problem

```
% docker run --rm -it ruby:3.1 /bin/bash
root@7e623884cfc0:/# cat > .rubocop.yml
AllCops:
  TargetRubyVersion: '3.1'
  NewCops: enable

root@7e623884cfc0:/# cat > a.rb
def foo(a=false, &block)
  bar(a, 1, &block)
end
root@7e623884cfc0:/# gem i rubocop
Fetching unicode-display_width-2.5.0.gem
Fetching ast-2.4.2.gem
Fetching ruby-progressbar-1.13.0.gem
Fetching rubocop-ast-1.30.0.gem
Fetching parser-3.3.0.4.gem
Fetching rubocop-1.60.1.gem
Fetching rainbow-3.1.1.gem
Fetching parallel-1.24.0.gem
Fetching regexp_parser-2.9.0.gem
Fetching language_server-protocol-3.17.0.3.gem
Successfully installed unicode-display_width-2.5.0
Successfully installed ruby-progressbar-1.13.0
Successfully installed ast-2.4.2
Successfully installed parser-3.3.0.4
Successfully installed rubocop-ast-1.30.0
Successfully installed regexp_parser-2.9.0
Successfully installed rainbow-3.1.1
Successfully installed parallel-1.24.0
Successfully installed language_server-protocol-3.17.0.3
Successfully installed rubocop-1.60.1
10 gems installed
root@7e623884cfc0:/# rubocop --only Style/ArgumentsForwarding -a a.rb
Inspecting 1 file
C

Offenses:

.rb:1:18: C: [Corrected] Style/ArgumentsForwarding: Use anonymous block arguments forwarding (&).
def foo(a=false, &block)
                 ^^^^^^
.rb:2:13: C: [Corrected] Style/ArgumentsForwarding: Use anonymous block arguments forwarding (&).
  bar(a, 1, &block)
            ^^^^^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /a.rb and caused by Style/ArgumentsForwarding
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:332:in `check_for_infinite_loop'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:315:in `block in iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:314:in `loop'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:164:in `block in file_offenses'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:189:in `file_offense_cache'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:163:in `file_offenses'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:154:in `process_file'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:134:in `each'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:134:in `reduce'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:134:in `each_inspected_file'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:120:in `inspect_files'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/runner.rb:73:in `run'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli.rb:118:in `run_command'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli.rb:125:in `execute_runners'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli.rb:51:in `block in run'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli.rb:77:in `profile_if_needed'
/usr/local/bundle/gems/rubocop-1.60.1/lib/rubocop/cli.rb:43:in `run'
/usr/local/bundle/gems/rubocop-1.60.1/exe/rubocop:19:in `block in <top (required)>'
/usr/local/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/usr/local/bundle/gems/rubocop-1.60.1/exe/rubocop:19:in `<top (required)>'
/usr/local/bundle/bin/rubocop:25:in `load'
/usr/local/bundle/bin/rubocop:25:in `<main>'
root@7e623884cfc0:/# cat a.rb
def foo(a=false, &)
  bar(a, 1, &)
end
```

## RuboCop version

```
root@7e623884cfc0:/# rubocop -V
1.60.1 (using Parser 3.3.0.4, rubocop-ast 1.30.0, running on ruby 3.1.4) [aarch64-linux]
```

**Comment by koic** [comment]
This issue is a dup with https://github.com/rubocop/rubocop/issues/12618#issuecomment-1896227199 with resolved in #12626. Thank you for the early feedback!
