### ISSUE TITLE
failed to load command: rubocop 

### ISSUE THREAD

**Issue by LandonSchropp** [rubocop/rubocop#12638]
I run `bundle exec rubocop --server` from my editor (Neovim + null_ls), and I get this error quite a bit:

```
 failed to load command: rubocop (/Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/bin/rubocop)
/Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:45:in `read
': No such file or directory @ rb_sysopen - /Users/landon/.cache/rubocop_cache/server/Users+landon+Development+anywhere/version (Errno:
:ENOENT)
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:45:in `read'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:45:in `incompatible_version?'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:34:in `ensure_server!'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:19:in `run'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/exe/rubocop:12:in `<top (required)>'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/bin/rubocop:25:in `load'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/bin/rubocop:25:in `<top (required)>'
```

A quick fix to temporarily get the problem working is to run the following:

``` shell
mkdir -p  ~/.cache/rubocop_cache/server/Users+landon+Development+anywhere
touch ~/.cache/rubocop_cache/server/Users+landon+Development+anywhere/status
```

## Expected behavior

This seems to be failing because either a file or directory Rubocop expects to exist doesn't.

## Actual behavior

`bundle exec rubocop --server` intermittently fails with this error when run via my editor.

Here's the output from `bundle exec rubocop --debug`:

```
bundler: failed to load command: rubocop (/Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/bin/rubocop)
/Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:57:in `read': No such file or directory @ rb_sysopen - /Users/landon/.cache/rubocop_cache/server/Users+landon+Development+anywhere/status (Errno::ENOENT)
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:57:in `read'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:57:in `status'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/lib/rubocop/server/client_command/exec.rb:28:in `run'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/gems/rubocop-1.60.1/exe/rubocop:12:in `<top (required)>'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/bin/rubocop:25:in `load'
        from /Users/landon/Development/anywhere/vendor/nix/gems/ruby/3.2.0/bin/rubocop:25:in `<top (required)>'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/bin/bundle:25:in `load'
        from /nix/store/fcm6ssrziahxypka38jm5kyrnbwaqd9f-ruby-3.2.2/bin/bundle:25:in `<main>'
```

## Steps to reproduce the problem

Unfortunately, I haven't found a reliable way to get the system into this state. This issue could be compounded by running Rubocop from a Nix environment. 

Hopefully, the fix is as simple as removing the assumption that the missing file/directory exists.

## RuboCop version

```
1.60.1 (using Parser 3.3.0.4, rubocop-ast 1.30.0, running on ruby 3.2.2) +server [arm64-darwin22]
  - rubocop-performance 1.19.1
  - rubocop-rails 2.22.2
  - rubocop-rspec 2.26.1
```

**Comment by JBJackle** [comment]
I have the same issue, I tried completely clearing my gems and reinstalling and everything. No idea why it even stopped working in the first place but I don't use nix so I'm assuming its not that.

**Comment by LandonSchropp** [comment]
Wow! Thank you @koic!
