### ISSUE TITLE
Incompatibility between `parser_prism` and `ruby_extractors` 

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop#12749]
When using the newly introduced prism parser and using a extension that modifies ruby_extractors, it looks like the extractors are not used.

## Steps to reproduce the problem

`.rubocop.yml`
```yml
require:
  - rubocop-erb

AllCops:
  TargetRubyVersion: 3.3
  ParserEngine: parser_prism
```

`test.html.erb`
```erb
<div>
  Hello!
</div>
<%= render "something" %>
```

I have added logging to the tokens being passed to the parser compatibility layer and its getting the whole source file literally:

```
LESS(1,0)-(1,1)("<")
IDENTIFIER(1,1)-(1,4)("div")
GREATER(1,4)-(1,5)(">")
IGNORED_NEWLINE(1,5)-(2,0)("\n")
METHOD_NAME(2,2)-(2,8)("Hello!")
NEWLINE(2,8)-(3,0)("\n")
LESS(3,0)-(3,1)("<")
REGEXP_BEGIN(3,1)-(3,2)("/")
STRING_CONTENT(3,2)-(5,0)("div>\n" + "<%= render \"something\" %>\n")
EOF(5,0)-(5,0)("")
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.62.0 (using Prism 0.24.0, rubocop-ast 1.31.1, running on ruby 3.3.0) [x86_64-linux]
  - rubocop-erb 0.3.1
```

**Comment by Earlopain** [comment]
Thank you, I have openend https://github.com/r7kamura/rubocop-erb/pull/28. I guess, the worst that should happen is that it would have been parsed with the parser gem instead of prism. But even after I have made this change and tested locally, it still shows the same behaviour.

I have the following file that actually makes prism raise during translation/lexing. Probably an error for the parser translator but I'm not going to fault it since its getting fed erb:

```rb
<div>
  <%= abc %>
  <%= abc title: "ABC" %>
  <%= rails_blob_url(submission_file.original, disposition: :inline) %>
  <%= submission_file_path(submission_file) %>
</div>
<%= render "something/1_and_2" %>
```

Here is the stracktrace:

<details><summary>Details</summary>
<p>

```
invalid value for Integer(): "1_"
<internal:kernel>:307:in `Integer'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.24.0/lib/prism/translation/parser/lexer.rb:244:in `to_a'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.24.0/lib/prism/translation/parser.rb:159:in `build_tokens'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.24.0/lib/prism/translation/parser.rb:89:in `tokenize'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.1/lib/rubocop/ast/processed_source.rb:224:in `tokenize'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.1/lib/rubocop/ast/processed_source.rb:219:in `parse'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.1/lib/rubocop/ast/processed_source.rb:47:in `initialize'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.1/lib/rubocop/ast/processed_source.rb:26:in `new'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.1/lib/rubocop/ast/processed_source.rb:26:in `from_file'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:482:in `get_processed_source'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:273:in `do_inspection_loop'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:163:in `file_offenses'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:154:in `process_file'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:134:in `each'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:134:in `reduce'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:120:in `inspect_files'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/runner.rb:73:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli/command.rb:11:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli.rb:118:in `run_command'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli.rb:125:in `execute_runners'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli.rb:51:in `block in run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/lib/rubocop/cli.rb:43:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/exe/rubocop:19:in `block in <top (required)>'
/home/user/.rbenv/versions/3.3.0/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.62.0/exe/rubocop:19:in `<top (required)>'
/home/user/.rbenv/versions/3.3.0/bin/rubocop:25:in `load'
/home/user/.rbenv/versions/3.3.0/bin/rubocop:25:in `<top (required)>'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
/home/user/.rbenv/versions/3.3.0/bin/bundle:25:in `load'
/home/user/.rbenv/versions/3.3.0/bin/bundle:25:in `<main>'
```

</p>
</details> 

`rubocop-erb` doesn't appear here so even with the change there looks to be something wrong in RuboCop itself.

Would you mind reopening this? I'm actually not able to.

**Comment by Earlopain** [comment]
Ok, so I believe this actually just a problem with the parser translation. Regardless of extensions or not, it will still try to parse the whole file first. https://github.com/rubocop/rubocop/blob/baa4a97656b452f02937efe261b55afa5cbc5bf6/lib/rubocop/runner.rb#L474-L483

This will end up calling `tokenize` on the parser. I guess the parser gem is just more robust here:
```
TOKENIZING: 
<div>
  <%= abc %>
  <%= abc title: "ABC" %>
  <%= rails_blob_url(submission_file.original, disposition: :inline) %>
  <%= submission_file_path(submission_file) %>
</div>
<%= render "something/1_and_2" %>

-------------
ast: nil
comments: []
tokens: [[:tLT, ["<", #<Parser::Source::Range /home/user/code/reverser/app/views/submission_files/_stats.html.erb 0...1>]]]
```

This somewhat goes against how I believed the extensions register themselves. Looks like it'll always try to tokenize before extensions, and only after that extensions get to do their thing. I'll just report this upstream then instead. If I've got something I'll edit links to these issues in this comment here.

Depending on if you want to track rubocop related prism issues here you can close or leave it open. Not sure how you want to handle these things.

**Comment by koic** [comment]
This issue has been resolved in Prism. OTOH, the rubocop.gemspec does not have a runtime dependency on Prism. Therefore, there is nothing that can be resolved from the RuboCop side. Please update Prism when a new version is released.
