### ISSUE TITLE
Infinite loop detected in the Rubocop Layout/LineLength rule

### ISSUE THREAD

**Issue by abratashov** [rubocop/rubocop#12995]
## Expected behavior

After running `Rubocop` on this my spec file, it crashes with error:
```sh
$ rubocop --debug --auto-correct --disable-uncorrectable spec/models/concerns/sanitizeable_spec.rb
...
Infinite loop detected in ./my_project/spec/models/concerns/sanitizeable_spec.rb and caused by Layout/LineLength, Metrics/BlockLength
Hint: Please update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.
Please check the latest version at https://rubygems.org/gems/rubocop.
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:322:in `block in iterate_until_no_changes'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:318:in `loop'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:318:in `iterate_until_no_changes'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:287:in `do_inspection_loop'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:168:in `block in file_offenses'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:193:in `file_offense_cache'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:167:in `file_offenses'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:158:in `process_file'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:139:in `block in each_inspected_file'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:138:in `each'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:138:in `reduce'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:138:in `each_inspected_file'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:124:in `inspect_files'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/runner.rb:77:in `run'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli/command.rb:11:in `run'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli/environment.rb:18:in `run'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli.rb:122:in `run_command'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli.rb:129:in `execute_runners'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli.rb:51:in `block in run'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli.rb:81:in `profile_if_needed'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/lib/rubocop/cli.rb:43:in `run'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/exe/rubocop:19:in `block in <top (required)>'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/alex/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.64.1/exe/rubocop:19:in `<top (required)>'
/home/alex/.asdf/installs/ruby/3.1.3/bin/rubocop:25:in `load'
/home/alex/.asdf/installs/ruby/3.1.3/bin/rubocop:25:in `<main>'
Finished in 61.03561436600285 seconds

```
## Actual behavior

Should work smoothly

## Steps to reproduce the problem

Gemfile contains:
```rb
  gem 'rubocop', '~> 1.64', require: false
```

Rubocop settings:
```yml
# .rubocop.yml

AllCops:
  TargetRubyVersion: 3.1

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 60
  Exclude:
    - 'db/migrate/**/*'
    - 'script/create_anons.rb'
    - 'script/create_news.rb'

Metrics/MethodLength:
  Max: 40

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
```

Test file is attached: 
[sanitizeable_spec.rb.txt](https://github.com/user-attachments/files/15842706/sanitizeable_spec.rb.txt)

## RuboCop version
```
$ [bundle exec] rubocop -V
1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.1.3) [x86_64-linux]
```

**Comment by Earlopain** [comment]
The issue here is that `disable-uncorrectable` inserts its comments into the word array like this

```rb
foo =
  %(
    foo
  )
# becomes =>
foo =
  %(
    # rubocop:todo Layout/LineLength
    foo
    # rubocop:enable Layout/LineLength
  )
# becomes =>
foo =
  %(
    # rubocop:todo Layout/LineLength
    # rubocop:todo Layout/LineLength
    foo
   # rubocop:enable Layout/LineLength
   # rubocop:enable Layout/LineLength
  )
# etc.
```

**Comment by ziaulrehman40** [comment]
I still face this issue, in some multiline array etc, not able to provide a complete reproduction ATM but on latest version 1.69.2, issue persists. (1.69.2 is released afetr the fix merged, so assuming the fix didn't completely fixed the issue)
