### ISSUE TITLE
cannot load such file -- rubocop-factory_bot

### ISSUE THREAD

**Issue by anko20094** [rubocop/rubocop#13008]
- Ruby 3.3.3 
- rubocop (1.64.1)
- rubocop-rspec (3.0.1)
- rubocop-rspec_rails (2.30.0)
- rubocop-factory_bot (2.26.1)

```ruby
# .rubocop.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker
  - rubocop-factory_bot
  - rubocop-rspec_rails
```

```ruby
# Gemfile

group :development do
  gem 'fasterer'
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-faker', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
```

Errors:
```
bundle exec rubocop
cannot load such file -- rubocop-factory_bot
```
```
bundle exec rubocop
cannot load such file -- rubocop-rspec_rails
```

**Comment by koic** [comment]
Can you show the result of `rubocop -V`?

**Comment by t-okamoto19** [comment]
I'm in the same situation.

`root@814e7f6eaded:/myapp# bundle exec rubocop -v
1.64.1`

**Comment by koic** [comment]
@t-okamoto19 Can you show the result of `bundle exec rubocop -V`? (Large `V`)

**Comment by anko20094** [comment]
Today it suddenly started work

```
$ rubocop -V
1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.3.3) +server [x86_64-linux]
  - rubocop-factory_bot 2.26.1
  - rubocop-faker 1.1.0
  - rubocop-performance 1.21.1
  - rubocop-rails 2.25.0
  - rubocop-rspec 3.0.1
  - rubocop-rspec_rails 2.30.0
```

**Comment by koic** [comment]
Thank you for sharing the log.

> 1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.3.3) +server [x86_64-linux]

Currently, the server mode (`+server`) doesn't yet support detecting upgrades or configuration changes. Please use `rubocop --restart-server`. For more information, please visit: https://docs.rubocop.org/rubocop/1.64/usage/server.html#restart-server

And FYI, I've opened issue #13004, which will likely cover many cases of this issue in the future.

**Comment by t-okamoto19** [comment]
> @t-okamoto19 Can you show the result of `bundle exec rubocop -V`? (Large `V`)

```
root@ccd61fec7e31:/myapp# ruby -v
ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]

root@ccd61fec7e31:/myapp# bundle exec rubocop -V
cannot load such file -- rubocop-factory_bot
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:39:in `rescue in load'
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:32:in `load'
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
<internal:kernel>:90:in `tap'


```
