### ISSUE TITLE
Style/SymbolProc crashes on a single file

### ISSUE THREAD

**Issue by jamesoneill997** [rubocop/rubocop#13023]
## Expected behavior
I'd expect it not to crash.

## Actual behavior
When running rubocop, it crashes because of some issue with Style/SymbolProc, but doesn't give much more detail.

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.
```
2140 files inspected, no offenses detected
configuration from ./.rubocop.yml
An error occurred while Style/SymbolProc cop was inspecting /dir/file.rb:86:64.

1 error occurred:
An error occurred while Style/SymbolProc cop was inspecting 
path_to_file/file.rb:86:64.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.3.3) +server [arm64-darwin23]
```
## Steps to reproduce the problem
I simply run rubocop using rubocop -d, all of the specs pass, but at the end, this single file crashes. If I add the file to Style/SymbolProc.Exclude, then the whole thing runs with no errors, it just seems to be something about one particular file

## RuboCop version
1.64.1

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
jamesoneill@Jamess-MBP:~/dir(git-branch) » bundle exec rubocop -V
1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.3.3) +server [arm64-darwin23]
  - rubocop-capybara 2.21.0
  - rubocop-factory_bot 2.26.1
  - rubocop-graphql 1.5.2
  - rubocop-performance 1.21.1
  - rubocop-rspec 3.0.1
  - rubocop-rspec_rails 2.30.0
```

**Comment by koic** [comment]
Can you provide the repro code?

**Comment by jamesoneill997** [comment]
I'm working on a private codebase, so I'm going to have to filter the content a little bit, but I'll give you as much context as I can.

So the line it's crashing on is reported as line 50 below:

```
50    validates_associated_with_hoisted_errors :association_a, if: ->(curr_object) do
51      curr_object.boolean_attribute_changed?
52    end
```


Validator:
```
      def validates_associated_with_hoisted_errors(*attr_names)
        validates_with AssociatedHoistingValidator, _merge_attributes(attr_names)
      end
 ```
 
 AssociatedHoistingValidator:
 ```
     class AssociatedHoistingValidator < ActiveModel::EachValidator
      def validate_each(record, attribute, value)
        (value.is_a?(Enumerable) || value.is_a?(ActiveRecord::Relation) ? value : [value]).each do |v|
          next if v.valid?

          v.errors.full_messages.each do |msg|
            message = format_message(msg, options[:format_message])
            record.errors.add(attribute, message, **options.merge(value:))
          end
        end
      end
  ```

Let me know if you need any more context on this.

**Comment by koic** [comment]
Unfortunately, the error doesn't seem to reproduce. Can you provide the error log of `rubocop -d` to the extent possible with your app?

**Comment by jamesoneill997** [comment]
I ran rubocop -d, the output is about 7k lines long, but I did find this somewhere in the middle, not sure if this is related maybe?

```
Parser::Source::TreeRewriter detected clobbering
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:210:in `call'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:210:in `block in check_fusible'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:208:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:208:in `check_fusible'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:188:in `analyse_hierarchy'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:112:in `place_in_hierarchy'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:107:in `do_combine'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter/action.rb:31:in `combine'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter.rb:400:in `combine'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parser-3.3.3.0/lib/parser/source/tree_rewriter.rb:194:in `replace'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:228:in `autocorrect_without_args'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:221:in `autocorrect'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:214:in `block in register_offense'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/base.rb:412:in `correct'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/base.rb:210:in `add_offense'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:214:in `register_offense'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:183:in `block in on_block'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:184:in `symbol_proc?'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/style/symbol_proc.rb:171:in `on_block'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:107:in `public_send'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:107:in `block (2 levels) in trigger_responding_cops'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:106:in `block in trigger_responding_cops'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:105:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:105:in `trigger_responding_cops'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:69:in `on_block'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:71:in `on_pair'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:71:in `on_hash'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:156:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:156:in `on_send'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:154:in `on_class'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:138:in `on_while'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cop/team.rb:98:in `investigate'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:349:in `block in inspect_file'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:348:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:348:in `flat_map'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:348:in `inspect_file'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:291:in `block in do_inspection_loop'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:325:in `block in iterate_until_no_changes'
<internal:kernel>:187:in `loop'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:318:in `iterate_until_no_changes'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:287:in `do_inspection_loop'
Loading cache from /Users/jamesoneill/.cache/rubocop_cache/415abff75bf945c49c89843e6705af7d0e6673d4/6d7a3b621ca1730e04accd938619e4bdab66cfb1/ddee944f21517f3338d4cdea87f263f0e724fd86
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:168:in `block in file_offenses'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:193:in `file_offense_cache'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:167:in `file_offenses'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:103:in `block in warm_cache'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:650:in `call_with_index'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:620:in `process_incoming_jobs'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:600:in `block in worker'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:591:in `fork'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:591:in `worker'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:582:in `block in create_workers'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:581:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:581:in `each_with_index'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:581:in `create_workers'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:520:in `work_in_processes'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:291:in `map'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/parallel-1.25.1/lib/parallel.rb:235:in `each'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:103:in `warm_cache'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/runner.rb:76:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli/command.rb:11:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli/environment.rb:18:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli.rb:122:in `run_command'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli.rb:129:in `execute_runners'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli.rb:51:in `block in run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli.rb:81:in `profile_if_needed'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/cli.rb:43:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/server_command/exec.rb:22:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/server_command/base.rb:24:in `block in run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/server_command/base.rb:23:in `chdir'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/server_command/base.rb:23:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/socket_reader.rb:33:in `block in read!'
Loading cache from /Users/jamesoneill/.cache/rubocop_cache/415abff75bf945c49c89843e6705af7d0e6673d4/6d7a3b621ca1730e04accd938619e4bdab66cfb1/fbfe16817cb2c222fae6c2eea86f02a116108fc1
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/helper.rb:26:in `redirect'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/socket_reader.rb:28:in `read!'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:86:in `read_socket'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:61:in `block in process_input'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/cache.rb:140:in `write_pid_file'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:60:in `process_input'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:49:in `block in detach_server'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:46:in `fork'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:46:in `detach_server'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/core.rb:38:in `start'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/client_command/start.rb:42:in `block in run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/cache.rb:127:in `acquire_lock'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/client_command/start.rb:29:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/client_command/restart.rb:20:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/cli.rb:98:in `run_command'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/cli.rb:83:in `process_arguments'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/lib/rubocop/server/cli.rb:49:in `run'
/Users/jamesoneill/.gem/ruby/3.3.3/gems/rubocop-1.64.1/exe/rubocop:8:in `<top (required)>'
/Users/jamesoneill/.gem/ruby/3.3.3/bin/rubocop:25:in `load'
/Users/jamesoneill/.gem/ruby/3.3.3/bin/rubocop:25:in `<main>'
```

**Comment by Earlopain** [comment]
This reproduces, `ActiveSupportExtensionsEnabled` must be false as it would otherwise produce no offense:
```rb
->(foo) do
  foo.bar
end
```
