### ISSUE TITLE
CodeLength undefined method `to_sym' for false

### ISSUE THREAD

**Issue by itay-grudev** [rubocop/rubocop#13158]
The following code throws the exception below, when `NewCops` are enabled.

https://github.com/rubocop/rubocop/blob/a47ca35cbd55c02e366618ece3bd4afceb966566/lib/rubocop/cop/mixin/code_length.rb#L27-L29

To help in debugging:

```
cop_config = {"Description"=>"Avoid methods longer than 10 lines of code.", "StyleGuide"=>"#short-methods", "Enabled"=>true, "VersionAdded"=>"0.25", "VersionChanged"=>"1.5", "CountComments"=>false, "Max"=>30, "CountAsOne"=>false, "AllowedMethods"=>[], "AllowedPatterns"=>[]}
```

so

```
Array(cop_config['CountAsOne']) # [false]
```

and there is no `to_sym` on `FalseClass`.

```
undefined method `to_sym' for false
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/mixin/code_length.rb:28:in `map'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/mixin/code_length.rb:28:in `count_as_one'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/mixin/code_length.rb:54:in `build_code_length_calculator'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/mixin/code_length.rb:35:in `check_code_length'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/metrics/method_length.rb:52:in `on_def'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:107:in `public_send'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:107:in `block (2 levels) in trigger_responding_cops'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:106:in `block in trigger_responding_cops'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:105:in `each'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:105:in `trigger_responding_cops'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:69:in `on_def'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.32.1/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.32.1/lib/rubocop/ast/traversal.rb:137:in `each'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.32.1/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.32.1/lib/rubocop/ast/traversal.rb:154:in `on_class'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:71:in `on_class'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.32.1/lib/rubocop/ast/traversal.rb:20:in `walk'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/commissioner.rb:87:in `investigate'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/team.rb:164:in `investigate_partial'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cop/team.rb:102:in `investigate'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:349:in `block in inspect_file'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:348:in `each'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:348:in `flat_map'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:348:in `inspect_file'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:291:in `block in do_inspection_loop'
~.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:325:in `block in iterate_until_no_changes'
<internal:kernel>:187:in `loop'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:318:in `iterate_until_no_changes'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:287:in `do_inspection_loop'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:168:in `block in file_offenses'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:193:in `file_offense_cache'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:167:in `file_offenses'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:158:in `process_file'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:139:in `block in each_inspected_file'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:138:in `each'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:138:in `reduce'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:138:in `each_inspected_file'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:124:in `inspect_files'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/runner.rb:77:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli/command.rb:11:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli/environment.rb:18:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli.rb:122:in `run_command'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli.rb:129:in `execute_runners'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli.rb:51:in `block in run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli.rb:81:in `profile_if_needed'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/cli.rb:43:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/server_command/exec.rb:22:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/server_command/base.rb:24:in `block in run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/server_command/base.rb:23:in `chdir'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/server_command/base.rb:23:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/socket_reader.rb:33:in `block in read!'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/helper.rb:26:in `redirect'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/socket_reader.rb:28:in `read!'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:90:in `read_socket'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:65:in `block in process_input'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/cache.rb:150:in `write_pid_file'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:64:in `process_input'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:53:in `block in detach_server'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:46:in `fork'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:46:in `detach_server'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:38:in `start'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/start.rb:42:in `block in run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/cache.rb:137:in `acquire_lock'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/start.rb:29:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/restart.rb:20:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/cli.rb:98:in `run_command'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/cli.rb:83:in `process_arguments'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/lib/rubocop/server/cli.rb:49:in `run'
~/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rubocop-1.65.1/exe/rubocop:8:in `<top (required)>'
~/.rbenv/versions/3.3.4/bin/rubocop:25:in `load'
~/.rbenv/versions/3.3.4/bin/rubocop:25:in `<main>'
```

**Comment by itay-grudev** [comment]
This was caused by the accidental usage of:
```
Metrics/MethodLength:
  CountAsOne: false
```
