### ISSUE TITLE
Flaky `RuboCop::TargetFinder` spec

### ISSUE THREAD

**Issue by viralpraxis** [rubocop/rubocop#13604]
--------

## Expected behavior

I expect all the tests to pass on JRuby.

## Actual behavior

`spec/rubocop/target_finder_spec.rb`  is flaky on JRuby 9.4.9.0:

```console
ASDF_RUBY_VERSION=jruby-9.4.9.0 be rspec --seed 37240

<SNIP>

RuboCop::TargetFinder#find(..., :all_file_types) when some paths are specified in the configuration Exclude and they are explicitly passed as arguments when it's forced to adhere file exclusion configuration when parent exclusion is ignored excludes files that are excluded on any level
     Failure/Error: expect(found_basenames).to eq(['ruby2.rb'])
     
       expected: ["ruby2.rb"]
            got: ["ruby1.rb", "ruby2.rb"]
     
       (compared using ==)
     Shared Example Group: "common behavior for #find" called from ./spec/rubocop/target_finder_spec.rb:350
     # ./spec/rubocop/target_finder_spec.rb:172:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:44:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block in <main>'

  3) RuboCop::TargetFinder#find(..., :only_recognized_file_types) when some paths are specified in the configuration Exclude and they are explicitly passed as arguments when it's forced to adhere file exclusion configuration when parent exclusion is ignored excludes files that are excluded on any level
     Failure/Error: expect(found_basenames).to eq(['ruby2.rb'])
     
       expected: ["ruby2.rb"]
            got: ["ruby1.rb", "ruby2.rb"]
     
       (compared using ==)
     Shared Example Group: "common behavior for #find" called from ./spec/rubocop/target_finder_spec.rb:321
     # ./spec/rubocop/target_finder_spec.rb:172:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:44:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `block in <main>'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block in <main>'
```

## Steps to reproduce the problem
`ASDF_RUBY_VERSION=jruby-9.4.9.0 be rspec --seed 37240`

Reproducible both at CI and local environment

Ruby: jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 20.0.2+9 on 20.0.2+9 +jit [x86_64-linux]

## RuboCop version

```console
$ [bundle exec] rubocop -V
1.69.2 (using Parser 3.3.5.0, rubocop-ast 1.36.2, analyzing as Ruby 2.7, running on jruby 3.1.4) [java]

$ ruby -v
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 20.0.2+9 on 20.0.2+9 +jit [x86_64-linux]
```

**Comment by Earlopain** [comment]
It's this: https://github.com/rubocop/rubocop/blob/d3eb9208cdd680d8688caf30c6d0e5959239026e/lib/rubocop/cli.rb#L174-L180

That state is global and not reset

**Comment by dvandersluis** [comment]
Thanks for doing the investigation, @Earlopain. I opened #13650 to fix it.
