### ISSUE TITLE
`Encoding::UndefinedConversionError`  on latest unicode-display_width 

### ISSUE THREAD

**Issue by viralpraxis** [rubocop/rubocop#13618]
## Expected behavior

I don't expect any exception.

## Actual behavior

An exception occur.

## Steps to reproduce the problem

```ruby
# coding: ASCII-8BIT
# frozen_string_literal: true

def test
  p 'ascii'
 p '€'
end
```

With `unicode-display_width (2.4.0)`:

```console
$ rubocop test.rb
Inspecting 1 file
C

Offenses:

test.rb:6:2: C: [Correctable] Layout/IndentationConsistency: Inconsistent indentation detected.
 p '€'
 ^^^^^^^
```

With `unicode-display_width (3.1.2)`:

```console
test.rb:6:2: C: [Correctable] Layout/IndentationConsistency: Inconsistent indentation detected.
 p '€'
"\xE2" from ASCII-8BIT to UTF-8
gems/3.3.0/gems/unicode-display_width-3.1.2/lib/unicode/display_width.rb:50:in `encode'
gems/3.3.0/gems/unicode-display_width-3.1.2/lib/unicode/display_width.rb:50:in `of'
rubocop/lib/rubocop/formatter/clang_style_formatter.rb:51:in `report_highlighted_area'
rubocop/lib/rubocop/formatter/clang_style_formatter.rb:30:in `report_offense'
rubocop/lib/rubocop/formatter/clang_style_formatter.rb:12:in `block in report_file'
rubocop/lib/rubocop/formatter/clang_style_formatter.rb:12:in `each'
rubocop/lib/rubocop/formatter/clang_style_formatter.rb:12:in `report_file'
```
## RuboCop version

```
$ [bundle exec] rubocop -V
1.69.2 (using Parser 3.3.5.0, rubocop-ast 1.36.2, analyzing as Ruby 2.7, running on ruby 3.3.6) [x86_64-linux]
```

**Comment by Earlopain** [comment]
Fixed with `unicode-display_width` 3.1.3: https://github.com/janlelis/unicode-display_width/pull/28
