### ISSUE TITLE
"An error occured while forking"; --only

### ISSUE THREAD

**Issue by MarcoCostantini** [rubocop/rubocop#7961]
An error occurred, and it was written to report here.
Furthermore, why the --only option is invalid?

```
$ rubocop --only  Performance,Require,Lint,Security,Style/EmptyCaseCondition  --require rubocop/require_tools --require rubocop-performance   /usr/lib/ruby/2.7.0/rubygems/installer_test_case.rb /usr/lib/ruby/2.7.0/rubygems/package/tar_test_case.rb /usr/lib/ruby/2.7.0/rubygems/test_case.rb  -d                                                                                          
For /usr/lib/ruby/2.7.0: Inspecting 3 files
Scanning /usr/lib/ruby/2.7.0/rubygems/installer_test_case.rb

invalid option: --only

minitest options:
    -h, --help                       Display this help.
        --no-plugins                 Bypass minitest plugin auto-loading (or set $MT_NO_PLUGINS).
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
    -e, --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
An error occurred while Require/MissingRequireStatement cop was inspecting /usr/lib/ruby/2.7.0/rubygems/installer_test_case.rb.
An error occured while forking
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:241:in `perform_in_fork'
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:178:in `check_timeline'
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:54:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:108:in `block (2 levels) in invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:107:in `block in invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:104:in `each'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:104:in `invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:42:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:124:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:112:in `offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:296:in `inspect_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:244:in `block in do_inspection_loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:276:in `block in iterate_until_no_changes'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:143:in `file_offense_cache'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:117:in `file_offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:108:in `process_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `reduce'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:73:in `inspect_files'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:39:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command.rb:10:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/environment.rb:17:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:65:in `run_command'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:72:in `execute_runners'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:41:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/exe/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/exe/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
.Scanning /usr/lib/ruby/2.7.0/rubygems/package/tar_test_case.rb

invalid option: --only

minitest options:
    -h, --help                       Display this help.
        --no-plugins                 Bypass minitest plugin auto-loading (or set $MT_NO_PLUGINS).
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
    -e, --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
An error occurred while Require/MissingRequireStatement cop was inspecting /usr/lib/ruby/2.7.0/rubygems/package/tar_test_case.rb.
An error occured while forking
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:241:in `perform_in_fork'
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:178:in `check_timeline'
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:54:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:108:in `block (2 levels) in invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:107:in `block in invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:104:in `each'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:104:in `invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:42:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:124:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:112:in `offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:296:in `inspect_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:244:in `block in do_inspection_loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:276:in `block in iterate_until_no_changes'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:143:in `file_offense_cache'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:117:in `file_offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:108:in `process_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `reduce'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:73:in `inspect_files'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:39:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command.rb:10:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/environment.rb:17:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:65:in `run_command'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:72:in `execute_runners'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:41:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/exe/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/exe/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
.Scanning /usr/lib/ruby/2.7.0/rubygems/test_case.rb
Note: Could not load simplecov:
cannot load such file -- simplecov
Check your dependencies, they could be circular
Note: Could not load rake/packagetask:
cannot load such file -- rake/packagetask
Check your dependencies, they could be circular
Note: Could not load builder/xchar:
cannot load such file -- builder/xchar
Check your dependencies, they could be circular
Note: Could not load rubygems/test_utilities:
uninitialized constant Gem::TestCase
Check your dependencies, they could be circular

invalid option: --only

minitest options:
    -h, --help                       Display this help.
        --no-plugins                 Bypass minitest plugin auto-loading (or set $MT_NO_PLUGINS).
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
    -e, --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
An error occurred while Require/MissingRequireStatement cop was inspecting /usr/lib/ruby/2.7.0/rubygems/test_case.rb.
An error occured while forking
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:241:in `perform_in_fork'
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:178:in `check_timeline'
/var/lib/gems/2.7.0/gems/rubocop-require_tools-0.1.2/lib/rubocop/cop/require/missing_require_statement.rb:54:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:108:in `block (2 levels) in invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:107:in `block in invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:104:in `each'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:104:in `invoke_custom_processing'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/commissioner.rb:42:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:124:in `investigate'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:112:in `offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:296:in `inspect_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:244:in `block in do_inspection_loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:276:in `block in iterate_until_no_changes'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:143:in `file_offense_cache'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:117:in `file_offenses'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:108:in `process_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `reduce'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:73:in `inspect_files'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:39:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/command.rb:10:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli/environment.rb:17:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:65:in `run_command'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:72:in `execute_runners'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:41:in `run'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/exe/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/var/lib/gems/2.7.0/gems/rubocop-0.82.0/exe/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
W

Offenses:

rubygems/test_case.rb:16:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue Gem::LoadError
^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:26:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue LoadError
^^^^^^^^^^^^^^^^
rubygems/test_case.rb:246:8: C: Performance/RedundantMatch: Use =~ in places where the MatchData returned by #match will not be used.
    if output.match(/\n/)
       ^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:246:8: C: Performance/RegexpMatch: Use match? instead of match when MatchData is not used.
    if output.match(/\n/)
       ^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:593:21: W: Lint/UnusedMethodArgument: Unused method argument - spec. If it's necessary, use _ or _spec as an argument name to indicate that it won't be used. You can also write as ask_if_ok(*) if you want the method to accept any arguments but don't care about them.
      def ask_if_ok(spec)
                    ^^^^
rubygems/test_case.rb:603:9: C: Performance/UnfreezeString: Use unary plus to get an unfrozen string literal.
    s = String.new
        ^^^^^^^^^^
rubygems/test_case.rb:614:15: C: Security/MarshalLoad: Avoid using Marshal.load.
      Marshal.load io.read
              ^^^^
rubygems/test_case.rb:951:28: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
      write_file File.join(*%W[gems #{@a2_pre.original_name} lib code.rb])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:955:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@a1.original_name}      lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:956:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@a2.original_name}      lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:957:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@a3a.original_name}     lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:958:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@a_evil9.original_name} lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:959:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@b2.original_name}      lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:960:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@c1_2.original_name}    lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:961:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@pl1.original_name}     lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:962:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@x.original_name}       lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:963:26: W: Lint/RedundantSplatExpansion: Pass array contents as separate arguments.
    write_file File.join(*%W[gems #{@dep_x.original_name}   lib code.rb])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:991:38: W: Lint/UnusedMethodArgument: Unused method argument - repo. If it's necessary, use _ or _repo as an argument name to indicate that it won't be used.
  def add_to_fetcher(spec, path=nil, repo=@gem_repo)
                                     ^^^^
rubygems/test_case.rb:1183:3: W: Lint/SuppressedException: Do not suppress exceptions.
  rescue Errno::ECHILD
  ^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1260:10: C: Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
      if %r'\A[-+:/=@,.\w]+\z' =~ path
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1429:30: W: Lint/UnusedMethodArgument: Unused method argument - platform. If it's necessary, use _ or _platform as an argument name to indicate that it won't be used.
    def load_spec(name, ver, platform, source)
                             ^^^^^^^^
rubygems/test_case.rb:1429:40: W: Lint/UnusedMethodArgument: Unused method argument - source. If it's necessary, use _ or _source as an argument name to indicate that it won't be used.
    def load_spec(name, ver, platform, source)
                                       ^^^^^^
rubygems/test_case.rb:1515:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue Gem::LoadError
^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1520:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue LoadError
^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1528:1: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
rescue LoadError, Gem::LoadError
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1528:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue LoadError, Gem::LoadError
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1534:1: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
rescue LoadError, Gem::LoadError
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rubygems/test_case.rb:1534:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue LoadError, Gem::LoadError
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

3 files inspected, 28 offenses detected

3 errors occurred:
An error occurred while Require/MissingRequireStatement cop was inspecting /usr/lib/ruby/2.7.0/rubygems/installer_test_case.rb.
An error occurred while Require/MissingRequireStatement cop was inspecting /usr/lib/ruby/2.7.0/rubygems/package/tar_test_case.rb.
An error occurred while Require/MissingRequireStatement cop was inspecting /usr/lib/ruby/2.7.0/rubygems/test_case.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.82.0 (using Parser 2.7.1.2, running on ruby 2.7.0 x86_64-linux-gnu)
Finished in 1.0753278330084868 seconds
```

**Comment by jonas054** [comment]
It's hard to say why this happens. Apparently `minitest` gets loaded and takes control of option parsing. Perhaps it's related to the `rubocop-require_tools` gem, since that's where the exception is raised. I doubt that it's useful to keep this issue open anyway.
