### ISSUE TITLE
Integration with Kakoune Lint throw errors

### ISSUE THREAD

**Issue by stacyharper** [rubocop/rubocop#8525]
Hello there,

I got a problem using rubocop in the Kakoune Lint module

I guess I just have to `set buffer lintcmd 'rubocop -f emacs'` then `:lint` but it logs ton of errors [here debug buffer](http://dav.misterbanal.net/9a9820e0-9070-4f38-9161-467b36068974.EisYpdtG2k.txt)

Doest anyone got the catch explaining why it does not work in this context ?

--------

## Expected behavior

It should lint the current buffer

## Actual behavior

Rubocop crash then the logs are pushed in the *debug* buffer

## Steps to reproduce the problem

* run a vanilla Kakoune session with the lint module (provided by default)
* open a Rails file (in my case, a controller)
* config the linter `set buffer lintcmd 'rubocop -f emacs'`
* run `:lint`

## It works sometime for no reason

```
:set buffer lintcmd 'rubocop -f emacs'
:lint # do not works, crash
:set buffer lintcmd 'rubocop -f emacs -l'
:lint # no warning nor errors
:set buffer lintcmd 'rubocop -f emacs'
:lint # works well
```

## RuboCop version

```
$ rubocop -v
0.88.0
```

**Comment by jonas054** [comment]
I installed Kakoune and was able to reproduce the problem. I didn't manage to find the root cause, though. What I noticed was, that the cops that crash are in extension gems rather than in RuboCop itself. In your [linked debug buffer](http://dav.misterbanal.net/9a9820e0-9070-4f38-9161-467b36068974.EisYpdtG2k.txt) it was Rails cops. By adding --debug to the `rubocop` command I could see 
```
Scanning /tmp/kak-lint.ola2iidt/sel-0/text/Gemfile
For /tmp/kak-lint.ola2iidt/sel-0/text: Default configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-1.18.2/config/default.yml
For /home/jonas/dev/rubocop: configuration from /home/jonas/dev/rubocop/.rubocop.yml
configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-performance-1.11.3/config/default.yml
configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-performance-1.11.3/config/default.yml
configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-rspec-2.4.0/config/default.yml
configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-rspec-2.4.0/config/default.yml
configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-rake-0.6.0/config/default.yml
Inheriting configuration from /home/jonas/dev/rubocop/.rubocop_todo.yml
undefined method `[]' for nil:NilClass
/home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-rspec-2.4.0/lib/rubocop/cop/rspec/base.rb:22:in `on_new_investigation'
/home/jonas/.rvm/gems/ruby-3.0.0/gems/rubocop-1.18.2/lib/rubocop/cop/commissioner.rb:153:in `block (2 levels) in invoke'
```
which indicates that configuration loading for the extensions isn't working, although it seems like all the right `default.yml` files have been read.

In the end, what worked for me was to follow the instruction at https://github.com/mawww/kakoune/wiki/Lint#rubocop which uses `set-option window lintcmd` rather than `set buffer lintcmd`.
