### ISSUE TITLE
Layout/SpaceAroundOperators Infinite loop 

### ISSUE THREAD

**Issue by hackhowtofaq** [rubocop/rubocop#8751]
```
rubocop stderr Infinite loop detected in /tmp/rubocopJQqypL/tmp.rb and caused by Layout/SpaceAroundOperators -> Layout/ExtraSpacing
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:300:in `check_for_infinite_loop'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:283:in `block in iterate_until_no_changes'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:282:in `loop'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:282:in `iterate_until_no_changes'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:251:in `do_inspection_loop'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:128:in `block in file_offenses'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:153:in `file_offense_cache'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:127:in `file_offenses'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:118:in `process_file'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:97:in `block in each_inspected_file'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:96:in `each'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:96:in `reduce'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:96:in `each_inspected_file'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:82:in `inspect_files'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/runner.rb:43:in `run'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli/command/execute_runner.rb:17:in 'run'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli/command.rb:11:in `run'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli/environment.rb:18:in `run'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli.rb:65:in `run_command'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli.rb:72:in `execute_runners'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/lib/rubocop/cli.rb:41:in `run'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/exe/rubocop:13:in `block in <top (required)>'
.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.91.0/exe/rubocop:12:in `<top (required)>'
.rbenv/versions/2.6.6/bin/rubocop:23:in `load'
.rbenv/versions/2.6.6/bin/rubocop:23:in `<main>'
```
I will try to create a small file demo but I cannot localize the issue in the code right now.

## RuboCop version
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.2, running on ruby 2.6.6 x86_64-linux)

Ty!

**Comment by marcandre** [comment]
A big file is ok too (just create a gist).

**Comment by hackhowtofaq** [comment]
I cannot copy the code just like that, sorry.

**Comment by dvandersluis** [comment]
@hackhowtofaq can you share your .rubocop.yml for `Layout/SpaceAroundOperators` and `Layout/ExtraSpacing`?

**Comment by hackhowtofaq** [comment]
@dvandersluis  yeap sure,

`.rubocop.yml`
```
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
# Rails:
#   Enabled: true
```

`Layout/SpaceAroundOperators`
```
Layout/SpaceAroundOperators:
  Enabled: true
```
`Layout/ExtraSpacing`
```
Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true
  Enabled: true
```

**Comment by michaelglass** [comment]
here's an example:

```
GameDetail.decode_tricks(super[3..super.length], game.players.length)
```

causes
```
Infinite loop detected in /Users/michaelglass/Documents/work/sauspiel/sauspiel-rails/app/bummerl/models/game_detail.rb and caused by Layout/SpaceAroundKeyword -> Layout/SpaceInsideRangeLiteral
```

default configuration for both

```
1.23.0 (using Parser 3.0.3.1, rubocop-ast 1.14.0, running on ruby 2.7.5 x86_64-darwin21)
  - rubocop-performance 1.11.1
  - rubocop-rails 2.9.1
  - rubocop-rake 0.5.1
  - rubocop-rspec 2.3.0
```
