### ISSUE TITLE
rubocop chokes on unuusal chars in extended regex with comments

### ISSUE THREAD

**Issue by michaelglass** [rubocop/rubocop#9056]
## Expected behavior
rubocop doesn't crash

## Actual behavior
```
$ rubocop file.rb --debug

For /: Default configuration from /_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/config/default.yml
Inspecting 1 file
Scanning /file.rb
.

0 files inspected, no offenses detected
incompatible character encodings: UTF-8 and ASCII-8BIT
/_build/gems/ruby/2.6.0/gems/regexp_parser-1.8.2/lib/regexp_parser/expression/subexpression.rb:49:in `join'
/_build/gems/ruby/2.6.0/gems/regexp_parser-1.8.2/lib/regexp_parser/expression/subexpression.rb:49:in `to_s'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/ext/regexp_node.rb:28:in `assign_properties'
/_build/gems/ruby/2.6.0/gems/ast-2.4.1/lib/ast/node.rb:75:in `initialize'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/node.rb:91:in `initialize'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/builder.rb:77:in `new'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/builder.rb:77:in `n'
/_build/gems/ruby/2.6.0/gems/parser-2.7.2.0/lib/parser/builders/default.rb:350:in `regexp_compose'
/_build/gems/ruby/2.6.0/gems/parser-2.7.2.0/lib/parser/ruby26.rb:5786:in `_reduce_449'
/nix/store/7knbg9848wkdifxrfzb9dfn6vpf7pwpf-ruby-2.6.6/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
/nix/store/7knbg9848wkdifxrfzb9dfn6vpf7pwpf-ruby-2.6.6/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
/_build/gems/ruby/2.6.0/gems/parser-2.7.2.0/lib/parser/base.rb:189:in `parse'
/_build/gems/ruby/2.6.0/gems/parser-2.7.2.0/lib/parser/base.rb:237:in `tokenize'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/processed_source.rb:207:in `tokenize'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/processed_source.rb:202:in `parse'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/processed_source.rb:38:in `initialize'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/processed_source.rb:20:in `new'
/_build/gems/ruby/2.6.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/processed_source.rb:20:in `from_file'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:390:in `get_processed_source'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:245:in `do_inspection_loop'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:132:in `block in file_offenses'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:157:in `file_offense_cache'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:131:in `file_offenses'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:122:in `process_file'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:100:in `each'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:100:in `reduce'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:100:in `each_inspected_file'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:86:in `inspect_files'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/runner.rb:47:in `run'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli/command.rb:11:in `run'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli/environment.rb:18:in `run'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli.rb:65:in `run_command'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli.rb:72:in `execute_runners'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/lib/rubocop/cli.rb:41:in `run'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/exe/rubocop:13:in `block in <top (required)>'
/_build/gems/ruby/2.6.0/gems/benchmark-0.1.0/lib/benchmark.rb:308:in `realtime'
/_build/gems/ruby/2.6.0/gems/rubocop-1.3.1/exe/rubocop:12:in `<top (required)>'
/bin/rubocop:29:in `load'
/bin/rubocop:29:in `<main>'
Finished in 0.1171780000149738 seconds
 I  !  impure  ~/D/w/NoRedInk   update-rubocop *~$-…  monolith                                        2137ms  Mon Nov 16 13:52:24 2020
```

## Steps to reproduce the problem
run rubocop on this regex:

```
/¡#≥
/x
```

## RuboCop version
```
$ rubocop -V
1.3.1 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.6.6 x86_64-darwin17)
```

(thank you!!)

**Comment by marcandre** [comment]
Looks like a bug in `regexp_parser` gem...

**Comment by michaelglass** [comment]
@marcandre repro'd / reported the issue there. Thank you for the nudge! Up to you whether you want to leave the issue open for visibility until the other issue is closed.

**Comment by marcandre** [comment]
Thank you 👍
Let's keep it open and see what happens; stalebot will remind me to check this out if nothing happens for a while

**Comment by michaelglass** [comment]
This appears to be fixed with the new regexp_parser. Closing it here.
