### ISSUE TITLE
Error when inspecting file and folder with different config .rubocop.yml

### ISSUE THREAD

**Issue by andreyruby** [rubocop/rubocop#9202]
I have this structure
- my_app
  - .rubocop.yml
  - spec
    - .rubocop.yml
 
Also spec/.rubocop.yml requires rubocop-rspec
```
require: rubocop-rspec
inherit_from: ../.rubocop.yml
```

When requesting to check separate files - everything is ok
```
$ bundle exec rubocop app/forms/comments/update_form.rb  spec/lib/facebook_api/me_spec.rb 
Inspecting 2 files
..
2 files inspected, no offenses detected
```

When requesting to check same file and folder (with same one file) - rubocop raises tons of errors (look like one for each rspec rule)

```
bundle exec rubocop app/forms/comments/update_form.rb  spec/lib/facebook_api/

Inspecting 2 files
An error occurred while RSpec/Capybara/CurrentPathExpectation cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/Capybara/FeatureMethods cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/Capybara/VisibilityMatcher cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/FactoryBot/AttributeDefinedStatically cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/FactoryBot/FactoryClassName cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/Rails/HttpStatus cop was inspecting forms/comments/update_form.rb.
An error occurred while RSpec/AlignLeftLetBrace cop was inspecting forms/comments/update_form.rb.
...
# DEBUG
For /home/some/ruby/my_app: configuration from /home/some/ruby/my_app/.rubocop.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.9.1/config/default.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.9.1/config/default.yml
Default configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/config/default.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.9.0/config/default.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.9.0/config/default.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/anycable-rails-1.0.4/lib/anycable/rails/compatibility/rubocop/config/default.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/anycable-rails-1.0.4/lib/anycable/rails/compatibility/rubocop/config/default.yml
For spec/lib/facebook_api: configuration from /home/some/ruby/my_app/spec/.rubocop.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.0.0/config/default.yml
configuration from /home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.0.0/config/default.yml
Inheriting configuration from /home/some/ruby/my_app/.rubocop.yml
AllCops/Exclude configuration from /home/some/ruby/my_app/.rubocop.yml
Inspecting 2 files
Scanning /home/some/ruby/my_app/app/forms/comments/update_form.rb
undefined method `[]' for nil:NilClass
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.0.0/lib/rubocop/cop/rspec/base.rb:22:in `on_new_investigation'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:157:in `block (2 levels) in invoke'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:156:in `block in invoke'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:155:in `each'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:155:in `invoke'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:84:in `investigate'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/team.rb:157:in `investigate_partial'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:286:in `loop'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:131:in `file_offenses'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:122:in `process_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:100:in `each'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:100:in `reduce'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:86:in `inspect_files'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:47:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command.rb:11:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli.rb:65:in `run_command'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli.rb:72:in `execute_runners'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli.rb:41:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/exe/rubocop:13:in `block in <top (required)>'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/exe/rubocop:12:in `<top (required)>'
/home/some/.rbenv/versions/2.7.2/bin/rubocop:23:in `load'
/home/some/.rbenv/versions/2.7.2/bin/rubocop:23:in `<top (required)>'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/home/some/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/some/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
undefined method `[]' for nil:NilClass
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.0.0/lib/rubocop/cop/rspec/base.rb:22:in `on_new_investigation'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:157:in `block (2 levels) in invoke'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:156:in `block in invoke'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:155:in `each'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:155:in `invoke'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/commissioner.rb:84:in `investigate'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/team.rb:157:in `investigate_partial'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:286:in `loop'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:131:in `file_offenses'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:122:in `process_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:100:in `each'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:100:in `reduce'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:86:in `inspect_files'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/runner.rb:47:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/command.rb:11:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli.rb:65:in `run_command'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli.rb:72:in `execute_runners'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/lib/rubocop/cli.rb:41:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/exe/rubocop:13:in `block in <top (required)>'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.6.0/exe/rubocop:12:in `<top (required)>'
/home/some/.rbenv/versions/2.7.2/bin/rubocop:23:in `load'
/home/some/.rbenv/versions/2.7.2/bin/rubocop:23:in `<top (required)>'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/home/some/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/home/some/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/some/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
undefined method `[]' for nil:NilClass
/home/some/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.0.0/lib/rubocop/cop/rspec/base.rb:22:in 
...
```

## RuboCop version

```
$ bundle exec rubocop -V
1.6.0 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.7.2 x86_64-linux)
  - rubocop-performance 1.9.1
  - rubocop-rails 2.9.0
```
Also there is rubocop-rspec v2.0.0, but it is nit listed as required only for /spec folder

**Comment by hiendinhngoc** [comment]
Did you fix your issue? I got the same errors.

**Comment by aglushkov** [comment]
It works for me when I move `require: rubocop-rspec` to main `rubocop.yml` file

**Comment by bbatsov** [comment]
Closing as stale — this edge case with multiple .rubocop.yml files and --force-exclusion hasn't had engagement in 5+ years. If the bug persists on a current version, please open a fresh issue with a reproducible example.
