### ISSUE TITLE
rubocop report SystemStackError Error on Ubuntu system

### ISSUE THREAD

**Issue by kewudu** [rubocop/rubocop#9270]
I have a ruby file on windows, when use rubocop to inspect this file on windows, it's ok, but when i copy this ruby file to ubuntu system, use the same version of rubocop,  rubocop report SystemStackError error.

--------

## Expected behavior

rubocop on Ubuntu system behave the the same as windows system.

## Actual behavior

rubocop report SystemStackError on Ubuntu.
```
ec2a03401f88:~/rubocop# rubocop ser_otn.rb --debug
For /root/rubocop: Default configuration from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-1.0.0/config/default.yml
Inspecting 1 file
Scanning /root/rubocop/ser_otn.rb
.

0 files inspected, no offenses detected
Traceback (most recent call last):
	240: from /usr/local/ruby/bin/rubocop:23:in `<main>'
	239: from /usr/local/ruby/bin/rubocop:23:in `load'
	238: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-1.0.0/exe/rubocop:12:in `<top (required)>'
	237: from /usr/local/ruby/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	236: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-1.0.0/exe/rubocop:13:in `block in <top (required)>'
	235: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-1.0.0/lib/rubocop/cli.rb:41:in `run'
	234: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-1.0.0/lib/rubocop/cli.rb:72:in `execute_runners'
	233: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-1.0.0/lib/rubocop/cli.rb:65:in `run_command'
	 ... 228 levels...
	  4: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.1.0/lib/rubocop/ast/node/mixin/descendence.rb:31:in `block in each_child_node'
	  3: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.1.0/lib/rubocop/ast/node.rb:133:in `complete!'
	  2: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.1.0/lib/rubocop/ast/node/mixin/descendence.rb:28:in `each_child_node'
	  1: from /usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.1.0/lib/rubocop/ast/node/mixin/descendence.rb:28:in `each'
/usr/local/ruby/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.1.0/lib/rubocop/ast/node/mixin/descendence.rb:31:in `block in each_child_node': stack level too deep (SystemStackError)
```

## Steps to reproduce the problem

copy my file ser_otn.rb to ubuntu system under /root/rubocop directory
then cd /root/rubocop directory
run rubocop ser_ont.rb

## RuboCop version

```
ec2a03401f88:~/rubocop# rubocop -V
1.0.0 (using Parser 2.7.2.0, rubocop-ast 1.1.0, running on ruby 2.6.3 x86_64-linux-musl)
ec2a03401f88:~/rubocop# 
```

```
I think this error may relate to the system memeory usage, but I am not sure.
My ubuntu system memroy usage:
```
```
ec2a03401f88:~/rubocop# free -m
             total       used       free     shared    buffers     cached
Mem:          7966       7185        781         81        518       3728
-/+ buffers/cache:       2938       5028
Swap:            0          0          0
```
ec2a03401f88:~/rubocop#

**Comment by dvandersluis** [comment]
What’s the contents of the file being scanned?

**Comment by kewudu** [comment]
> hat’s the contents of the file being scanned

the file scanned is  604KB with 14264 lines of ruby code inside

**Comment by bbatsov** [comment]
There's no limit to RuboCop's ability! 😉 That being said - in a file this big you're more likely to run into some bug, as it happened in your case. I guess that's something you can't really share for repro purposes, right?

**Comment by koic** [comment]
Due to a lack of activity, I'll close this issue. If the problem continues, please feel free to reopen it with additional information.
