### ISSUE TITLE
Unable to add entities alongside to ERB processing

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop/rubocop#9763]
Roots: #7920 (/cc @jonas054 )

I want to have referenced exclusion **and** manual additions.

--------

## Expected behavior

No errors, RuboCop ignores manual typed files.

## Actual behavior

```yaml
AllCops:
  Exclude:
    - Task.rb
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
      - <%= path.sub(/^!! /, '') %>
    <% end %>
```

ignores excluding `Task.rb`.

```yaml
AllCops:
  Exclude:
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
      - <%= path.sub(/^!! /, '') %>
    <% end %>
    - Task.rb
```

raises an exception:

```
> bundle exec rubocop
(/home/alex/Projects/ruby/job_tests/hoodies/.rubocop.yml): did not find expected key while parsing a block mapping at line 10 column 3
/home/alex/.rbenv/versions/3.0.1/lib/ruby/3.0.0/psych.rb:456:in `parse'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/3.0.0/psych.rb:456:in `parse_stream'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/3.0.0/psych.rb:390:in `parse'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/yaml_duplication_checker.rb:12:in `check'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader.rb:225:in `check_duplication'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader.rb:61:in `load_yaml_configuration'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader.rb:41:in `load_file'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_store.rb:68:in `for_dir'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/config_store.rb:47:in `for_pwd'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/cli.rb:126:in `apply_default_formatter'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/lib/rubocop/cli.rb:40:in `run'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/exe/rubocop:12:in `block in <top (required)>'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rubocop-1.13.0/exe/rubocop:12:in `<top (required)>'
/home/alex/.rbenv/versions/3.0.1/bin/rubocop:23:in `load'
/home/alex/.rbenv/versions/3.0.1/bin/rubocop:23:in `<top (required)>'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
/home/alex/.rbenv/versions/3.0.1/bin/bundle:23:in `load'
/home/alex/.rbenv/versions/3.0.1/bin/bundle:23:in `<main>'
```

## Steps to reproduce the problem

Configs are above, file (`Task.rb`) just should contain any offenses.

## RuboCop version

```
bundle exec rubocop -V
1.13.0 (using Parser 3.0.1.1, rubocop-ast 1.5.0, running on ruby 3.0.1 x86_64-linux)
  - rubocop-performance 1.11.1
```

**Comment by dvandersluis** [comment]
Shot in the dark but it might be that the alignment of the `-` list is different inside the loop than for your `Task.rb` item?

**Comment by dvandersluis** [comment]
Yeah I get the same error when trying to parse this:

```yaml
Foo:
  Bar:
    - x
    - y
    - z
  - a
```

```
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 3
from /Users/daniel/.rbenv/versions/3.0.1/lib/ruby/3.0.0/psych.rb:456:in `parse'
```

**Comment by dvandersluis** [comment]
Either unindent `- <%= path.sub(/^!! /, '') %>` one step, or indent `- Task.rb` one step and your config should work.

**Comment by AlexWayfer** [comment]
@dvandersluis oh, I tried something similar, but not exactly correct, sorry, thank you.
