### ISSUE TITLE
Many infinite loop issues when using `--disable-uncorrectable` flag

### ISSUE THREAD

**Issue by thisismydesign** [rubocop/rubocop#9922]
## Expected behavior

No errors or skip errors and continue running.

## Actual behavior

Using `rubocop -a --disable-uncorrectable` a big project with no rubocop in the past results in many files running into infinite loops. Most often around `Metrics/AbcSize` and `Metrics/MethodLength`.

Using `rubocop -a` works.

## Steps to reproduce the problem

I'll see if I can share code, but for now, I'm just curious to know if this is a known issue.

```
$ [bundle exec] rubocop -V
1.18.3
```

**Comment by jonas054** [comment]
Even if you can't share code, could you share the output of `rubocop`?

**Comment by thisismydesign** [comment]
Sorry for the delay, just got approval to post the code. Here's a shorter file that reproduces the issue for me. Note, this happens for many files in fact.

`bundle exec rubocop app/controllers/newsletter_recommendations_controller.rb -a --disable-uncorrectable`

```rb
class NewsletterRecommendationsController < ApplicationController
  before_action :authenticate_user!

  def show
    # NOTE: admin logged-in-as not compatible (for now).
    raise "Unimplemented" if warden.authenticated?(scope: :admin_user)

    current_manager = current_user.manager

    raise ActiveRecord::RecordNotFound unless current_manager.present?

    newsletter_recommendation =
      NewsletterRecommendation.find_by(uuid: params[:uuid])

    raise ActiveRecord::RecordNotFound unless newsletter_recommendation

    employee =
      employee.find_for_company(
        newsletter_recommendation.employee_id,
        manager: current_manager,
        create_intro: true
      )

    intro = employee.introductions.where(manager_id: current_manager.id).last

    newsletter_recommendation.associate_introduction(intro)

    # NOTE: newsletter has a 1:1 relation between uuid and record rather than a uuid per result set
    rank = 0
    employee_id_with_tracking = "#{employee.id}-#{newsletter_recommendation.uuid}-#{rank}"

    respond_to do |format|
      format.html { redirect_to company_employee_path(employee_id_with_tracking) }
    end
  end
end
```

And here's the trace:

```
Inspecting 1 file
C

Offenses:

app/controllers/newsletter_recommendations_controller.rb:4:3: C: [Todo] Metrics/AbcSize: Assignment Branch Condition size for show is too high. [<7, 24, 3> 25.18/17]
  def show ...
  ^^^^^^^^
app/controllers/newsletter_recommendations_controller.rb:4:3: C: [Todo] Metrics/MethodLength: Method has too many lines. [19/10]
  def show ...
  ^^^^^^^^
app/controllers/newsletter_recommendations_controller.rb:4:12: C: [Corrected] Style/DoubleCopDisableDirective: More than one disable comment on one line.
  def show # rubocop:todo Metrics/AbcSize # rubocop:todo Metrics/MethodLength
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/controllers/newsletter_recommendations_controller.rb:6:11: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    raise "Unimplemented" if warden.authenticated?(scope: :admin_user)
          ^^^^^^^^^^^^^^^

0 files inspected, 4 offenses detected, 4 offenses corrected
Infinite loop detected in /app/app/controllers/newsletter_recommendations_controller.rb and caused by Metrics/AbcSize, Metrics/MethodLength, Style/DoubleCopDisableDirective
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:299:in `check_for_infinite_loop'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:282:in `block in iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:281:in `loop'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:281:in `iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:250:in `do_inspection_loop'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:130:in `block in file_offenses'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:155:in `file_offense_cache'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:129:in `file_offenses'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:120:in `process_file'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:100:in `each'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:100:in `reduce'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:100:in `each_inspected_file'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:86:in `inspect_files'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/runner.rb:47:in `run'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli.rb:65:in `run_command'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli.rb:72:in `execute_runners'
/usr/local/bundle/gems/rubocop-1.18.3/lib/rubocop/cli.rb:41:in `run'
/usr/local/bundle/gems/rubocop-1.18.3/exe/rubocop:12:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/rubocop-1.18.3/exe/rubocop:12:in `<top (required)>'
/usr/local/bundle/bin/rubocop:23:in `load'
/usr/local/bundle/bin/rubocop:23:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

Our `ruboyop.yml`

```
require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
  - "db/schema.rb"
  - "vendor/**/*"
  - "search-tracking/db/schema.rb"

# Documentation not enforced
Style/Documentation:
  Enabled: false
```

**Comment by jonas054** [comment]
Thanks for the report @thisismydesign. I'll try to fix it.

**Comment by thisismydesign** [comment]
@jonas054 Thanks a lot for the quick fix! Could you ping this thread when the fix is released?

**Comment by jonas054** [comment]
@thisismydesign Ping! RuboCop 1.18.4 has been released.

**Comment by thisismydesign** [comment]
Thanks @jonas054!
